/* THIS FILE WAS AUTOMATICALLY GENERATED BY inline_grammar.py */
#include "duckdb/parser/peg/keyword_helper.hpp"
#include "duckdb/parser/simplified_token.hpp"

#include "duckdb/common/case_insensitive_map.hpp"

#include <iterator>
#include <string_view>

namespace duckdb {
namespace {

constexpr std::string_view kReservedKeywords[] = {
    "all",        "analyse",      "analyze",     "and",       "any",       "array",    "as",         "asc",
    "asymmetric", "both",         "case",        "cast",      "check",     "collate",  "column",     "constraint",
    "create",     "default",      "deferrable",  "desc",      "describe",  "distinct", "do",         "else",
    "end",        "except",       "false",       "fetch",     "for",       "foreign",  "from",       "group",
    "having",     "in",           "initially",   "intersect", "into",      "lambda",   "lateral",    "leading",
    "limit",      "not",          "null",        "offset",    "on",        "only",     "or",         "order",
    "pivot",      "pivot_longer", "pivot_wider", "placing",   "primary",   "qualify",  "references", "returning",
    "select",     "show",         "some",        "summarize", "symmetric", "table",    "then",       "to",
    "trailing",   "true",         "union",       "unique",    "unpivot",   "using",    "variadic",   "when",
    "where",      "window",       "with",
};
constexpr std::string_view kUnreservedKeywords[] = {
    "abort",        "absolute",     "access",       "action",        "add",          "admin",
    "after",        "aggregate",    "also",         "alter",         "always",       "assertion",
    "assignment",   "at",           "atomic",       "attach",        "attribute",    "backward",
    "before",       "begin",        "cache",        "call",          "called",       "cascade",
    "cascaded",     "catalog",      "centuries",    "century",       "chain",        "characteristics",
    "checkpoint",   "class",        "close",        "cluster",       "comment",      "comments",
    "commit",       "committed",    "compression",  "configuration", "conflict",     "connect",
    "connection",   "constraints",  "content",      "continue",      "conversion",   "copy",
    "cost",         "csv",          "cube",         "current",       "cursor",       "cycle",
    "data",         "database",     "day",          "days",          "deallocate",   "decade",
    "decades",      "declare",      "defaults",     "deferred",      "definer",      "delete",
    "delimiter",    "delimiters",   "depends",      "detach",        "dictionary",   "disable",
    "discard",      "disconnect",   "document",     "domain",        "double",       "drop",
    "each",         "enable",       "encoding",     "encrypted",     "enum",         "error",
    "escape",       "event",        "exclude",      "excluding",     "exclusive",    "execute",
    "explain",      "export",       "export_state", "extension",     "extensions",   "external",
    "family",       "filter",       "first",        "following",     "force",        "forward",
    "function",     "functions",    "global",       "grant",         "granted",      "groups",
    "handler",      "header",       "hold",         "hour",          "hours",        "identity",
    "if",           "ignore",       "immediate",    "immutable",     "implicit",     "import",
    "include",      "including",    "increment",    "index",         "indexes",      "inherit",
    "inherits",     "inline",       "input",        "insensitive",   "insert",       "install",
    "instead",      "invoker",      "isolation",    "json",          "key",          "label",
    "language",     "large",        "last",         "leakproof",     "level",        "listen",
    "load",         "local",        "location",     "lock",          "locked",       "logged",
    "macro",        "mapping",      "match",        "matched",       "materialized", "maxvalue",
    "merge",        "method",       "microsecond",  "microseconds",  "millennia",    "millennium",
    "millisecond",  "milliseconds", "minute",       "minutes",       "minvalue",     "mode",
    "month",        "months",       "move",         "name",          "names",        "new",
    "next",         "no",           "nothing",      "notify",        "nowait",       "nulls",
    "object",       "of",           "off",          "oids",          "old",          "operator",
    "option",       "options",      "ordinality",   "others",        "over",         "overriding",
    "owned",        "owner",        "parallel",     "parser",        "partial",      "partition",
    "partitioned",  "passing",      "password",     "percent",       "persistent",   "plans",
    "policy",       "pragma",       "preceding",    "prepare",       "prepared",     "preserve",
    "prior",        "privileges",   "procedural",   "procedure",     "program",      "publication",
    "quarter",      "quarters",     "quote",        "range",         "read",         "reassign",
    "recheck",      "recursive",    "ref",          "referencing",   "refresh",      "reindex",
    "relative",     "release",      "rename",       "repeatable",    "replace",      "replica",
    "reset",        "respect",      "restart",      "restrict",      "return",       "returns",
    "revoke",       "role",         "rollback",     "rollup",        "rows",         "rule",
    "sample",       "savepoint",    "schema",       "schemas",       "scope",        "scroll",
    "search",       "second",       "seconds",      "secret",        "security",     "sequence",
    "sequences",    "serializable", "server",       "session",       "set",          "sets",
    "share",        "simple",       "skip",         "snapshot",      "sorted",       "source",
    "sql",          "stable",       "standalone",   "start",         "statement",    "statistics",
    "stdin",        "stdout",       "storage",      "stored",        "strict",       "strip",
    "subscription", "sysid",        "system",       "tables",        "tablespace",   "target",
    "temp",         "template",     "temporary",    "text",          "ties",         "transaction",
    "transform",    "trigger",      "truncate",     "trusted",       "type",         "types",
    "unbounded",    "uncommitted",  "unencrypted",  "unknown",       "unlisten",     "unlogged",
    "until",        "update",       "use",          "user",          "vacuum",       "valid",
    "validate",     "validator",    "value",        "variable",      "varying",      "version",
    "view",         "views",        "virtual",      "volatile",      "week",         "weeks",
    "whitespace",   "within",       "without",      "work",          "wrapper",      "write",
    "xml",          "year",         "years",        "yes",           "zone",
};
constexpr std::string_view kColNameKeywords[] = {
    "between",       "bigint",   "bit",     "boolean",       "char",         "character",  "coalesce",  "columns",
    "dec",           "decimal",  "exists",  "extract",       "float",        "generated",  "grouping",  "grouping_id",
    "inout",         "int",      "integer", "interval",      "map",          "national",   "nchar",     "none",
    "nullif",        "numeric",  "out",     "overlay",       "position",     "precision",  "real",      "row",
    "setof",         "smallint", "struct",  "substring",     "time",         "timestamp",  "treat",     "trim",
    "try_cast",      "values",   "varchar", "xmlattributes", "xmlconcat",    "xmlelement", "xmlexists", "xmlforest",
    "xmlnamespaces", "xmlparse", "xmlpi",   "xmlroot",       "xmlserialize", "xmltable",
};
constexpr std::string_view kTypeFuncKeywords[] = {
    "anti",   "asof",    "authorization", "binary",      "by",       "collation", "columns",  "concurrently", "cross",
    "freeze", "full",    "generated",     "glob",        "ilike",    "inner",     "is",       "isnull",       "join",
    "left",   "like",    "map",           "natural",     "notnull",  "outer",     "overlaps", "positional",   "right",
    "semi",   "similar", "struct",        "tablesample", "try_cast", "unpack",    "verbose",
};
constexpr std::string_view kTypeNameKeywords[] = {
    "anti",  "asof",   "authorization", "binary",      "by",       "collation", "columns",  "concurrently",
    "cross", "freeze", "full",          "glob",        "ilike",    "inner",     "is",       "isnull",
    "join",  "left",   "like",          "natural",     "notnull",  "outer",     "overlaps", "positional",
    "right", "semi",   "similar",       "tablesample", "try_cast", "unpack",    "verbose",
};

const case_insensitive_set_view_t kReservedSet(std::begin(kReservedKeywords), std::end(kReservedKeywords));
const case_insensitive_set_view_t kUnreservedSet(std::begin(kUnreservedKeywords), std::end(kUnreservedKeywords));
const case_insensitive_set_view_t kColNameSet(std::begin(kColNameKeywords), std::end(kColNameKeywords));
const case_insensitive_set_view_t kTypeFuncSet(std::begin(kTypeFuncKeywords), std::end(kTypeFuncKeywords));
const case_insensitive_set_view_t kTypeNameSet(std::begin(kTypeNameKeywords), std::end(kTypeNameKeywords));

} // namespace

bool peg::KeywordCategoryType(std::string_view text, PEGKeywordCategory type) {
	switch (type) {
	case PEGKeywordCategory::KEYWORD_RESERVED:
		return kReservedSet.contains(text);
	case PEGKeywordCategory::KEYWORD_UNRESERVED:
		return kUnreservedSet.contains(text);
	case PEGKeywordCategory::KEYWORD_TYPE_FUNC:
		return kTypeFuncSet.contains(text);
	case PEGKeywordCategory::KEYWORD_COL_NAME:
		return kColNameSet.contains(text);
	case PEGKeywordCategory::KEYWORD_TYPE_NAME:
		return kTypeNameSet.contains(text);
	default:
		return false;
	}
}

bool peg::IsKeyword(std::string_view text) {
	return kReservedSet.contains(text) || kUnreservedSet.contains(text) || kColNameSet.contains(text) ||
	       kTypeFuncSet.contains(text);
}

vector<ParserKeyword> peg::KeywordList() {
	vector<ParserKeyword> result;
	for (auto kw : kReservedKeywords) {
		result.push_back({string(kw), KeywordCategory::KEYWORD_RESERVED});
	}
	for (auto kw : kUnreservedKeywords) {
		result.push_back({string(kw), KeywordCategory::KEYWORD_UNRESERVED});
	}
	for (auto kw : kTypeFuncKeywords) {
		result.push_back({string(kw), KeywordCategory::KEYWORD_TYPE_FUNC});
	}
	for (auto kw : kColNameKeywords) {
		result.push_back({string(kw), KeywordCategory::KEYWORD_COL_NAME});
	}
	return result;
}
} // namespace duckdb
