//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_serialization.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#include "duckdb/common/serializer/serializer.hpp"
#include "duckdb/common/serializer/deserializer.hpp"
#include "duckdb/catalog/dependency.hpp"
#include "duckdb/catalog/dependency_list.hpp"

namespace duckdb {

void CatalogEntryInfo::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<CatalogType>(100, "type", type);
	serializer.WritePropertyWithDefault<Identifier>(101, "schema", schema);
	serializer.WritePropertyWithDefault<Identifier>(102, "name", name);
	serializer.WritePropertyWithDefault<idx_t>(103, "oid", oid, 0);
}

CatalogEntryInfo CatalogEntryInfo::Deserialize(Deserializer &deserializer) {
	CatalogEntryInfo result;
	deserializer.ReadProperty<CatalogType>(100, "type", result.type);
	deserializer.ReadPropertyWithDefault<Identifier>(101, "schema", result.schema);
	deserializer.ReadPropertyWithDefault<Identifier>(102, "name", result.name);
	result.oid = deserializer.ReadPropertyWithExplicitDefault<idx_t>(103, "oid", 0);
	return result;
}

void DependencyPiece::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<uint8_t>(100, "kind", static_cast<uint8_t>(kind), 0);
	serializer.WritePropertyWithDefault<idx_t>(101, "sub_object", sub_object, DConstants::INVALID_INDEX);
}

DependencyPiece DependencyPiece::Deserialize(Deserializer &deserializer) {
	DependencyPiece result;
	result.kind = static_cast<DependencyPieceKind>(deserializer.ReadPropertyWithExplicitDefault<uint8_t>(100, "kind", 0));
	result.sub_object = deserializer.ReadPropertyWithExplicitDefault<idx_t>(101, "sub_object", DConstants::INVALID_INDEX);
	return result;
}

void LogicalDependency::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<CatalogEntryInfo>(100, "entry", entry);
	serializer.WritePropertyWithDefault<Identifier>(101, "catalog", catalog);
	serializer.WritePropertyWithDefault<vector<DependencyPiece>>(102, "pieces", pieces, vector<DependencyPiece>());
}

LogicalDependency LogicalDependency::Deserialize(Deserializer &deserializer) {
	auto entry = deserializer.ReadProperty<CatalogEntryInfo>(100, "entry");
	auto catalog = deserializer.ReadPropertyWithDefault<Identifier>(101, "catalog");
	LogicalDependency result(deserializer.TryGet<Catalog>(), entry, std::move(catalog));
	result.pieces = deserializer.ReadPropertyWithExplicitDefault<vector<DependencyPiece>>(102, "pieces", vector<DependencyPiece>());
	return result;
}

void LogicalDependencyList::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<create_info_set_t>(100, "set", set);
}

LogicalDependencyList LogicalDependencyList::Deserialize(Deserializer &deserializer) {
	LogicalDependencyList result;
	deserializer.ReadProperty<create_info_set_t>(100, "set", result.set);
	return result;
}

} // namespace duckdb
