//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_serialization.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#include "duckdb/common/serializer/serializer.hpp"
#include "duckdb/common/serializer/deserializer.hpp"
#include "duckdb/storage/wal_entry.hpp"

namespace duckdb {

void WALArtifact::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<CatalogType>(101, "catalog_type", catalog_type);
	serializer.WritePropertyWithDefault<idx_t>(102, "catalog_oid", catalog_oid);
	serializer.WritePropertyWithDefault<idx_t>(103, "oid", oid);
	serializer.WritePropertyWithDefault<vector<string>>(104, "paths", paths);
}

WALArtifact WALArtifact::Deserialize(Deserializer &deserializer) {
	WALArtifact result;
	deserializer.ReadProperty<CatalogType>(101, "catalog_type", result.catalog_type);
	deserializer.ReadPropertyWithDefault<idx_t>(102, "catalog_oid", result.catalog_oid);
	deserializer.ReadPropertyWithDefault<idx_t>(103, "oid", result.oid);
	deserializer.ReadPropertyWithDefault<vector<string>>(104, "paths", result.paths);
	return result;
}

void WALCheckpoint::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<MetaBlockPointer>(101, "meta_block", meta_block);
}

WALCheckpoint WALCheckpoint::Deserialize(Deserializer &deserializer) {
	WALCheckpoint result;
	deserializer.ReadProperty<MetaBlockPointer>(101, "meta_block", result.meta_block);
	return result;
}

void WALCommitPrepared::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<hugeint_t>(101, "txid", txid);
	serializer.WritePropertyWithDefault<vector<idx_t>>(102, "participant_oids", participant_oids);
	serializer.WritePropertyWithDefault<vector<idx_t>>(103, "participant_generations", participant_generations);
}

WALCommitPrepared WALCommitPrepared::Deserialize(Deserializer &deserializer) {
	WALCommitPrepared result;
	deserializer.ReadProperty<hugeint_t>(101, "txid", result.txid);
	deserializer.ReadPropertyWithDefault<vector<idx_t>>(102, "participant_oids", result.participant_oids);
	deserializer.ReadPropertyWithDefault<vector<idx_t>>(103, "participant_generations", result.participant_generations);
	return result;
}

void WALCreateDatabase::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "database", database);
}

WALCreateDatabase WALCreateDatabase::Deserialize(Deserializer &deserializer) {
	WALCreateDatabase result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "database", result.database);
	return result;
}

void WALCreateForeignServer::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "server", server);
}

WALCreateForeignServer WALCreateForeignServer::Deserialize(Deserializer &deserializer) {
	WALCreateForeignServer result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "server", result.server);
	return result;
}

void WALCreateMacro::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "macro", macro);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "macro", macro);
	}
}

WALCreateMacro WALCreateMacro::Deserialize(Deserializer &deserializer) {
	WALCreateMacro result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "macro", result.macro);
	return result;
}

void WALCreateRole::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "role", role);
}

WALCreateRole WALCreateRole::Deserialize(Deserializer &deserializer) {
	WALCreateRole result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "role", result.role);
	return result;
}

void WALCreateSchema::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", schema);
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(102, "qualified_name", qualified_name, QualifiedName());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(16484, "info", info);
	}
}

WALCreateSchema WALCreateSchema::Deserialize(Deserializer &deserializer) {
	WALCreateSchema result;
	deserializer.ReadPropertyWithDefault<Identifier>(101, "schema", result.schema);
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(102, "qualified_name", result.qualified_name, QualifiedName());
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(16484, "info", result.info);
	return result;
}

void WALCreateSequence::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "sequence", sequence);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "sequence", sequence);
	}
}

WALCreateSequence WALCreateSequence::Deserialize(Deserializer &deserializer) {
	WALCreateSequence result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "sequence", result.sequence);
	return result;
}

void WALCreateTable::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "table", table);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "table", table);
	}
}

WALCreateTable WALCreateTable::Deserialize(Deserializer &deserializer) {
	WALCreateTable result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "table", result.table);
	return result;
}

void WALCreateTableMacro::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "table_macro", table_macro);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "table_macro", table_macro);
	}
}

WALCreateTableMacro WALCreateTableMacro::Deserialize(Deserializer &deserializer) {
	WALCreateTableMacro result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "table_macro", result.table_macro);
	return result;
}

void WALCreateTokenizer::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "tokenizer", tokenizer);
}

WALCreateTokenizer WALCreateTokenizer::Deserialize(Deserializer &deserializer) {
	WALCreateTokenizer result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "tokenizer", result.tokenizer);
	return result;
}

void WALCreateTrigger::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "trigger", trigger);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "trigger", trigger);
	}
}

WALCreateTrigger WALCreateTrigger::Deserialize(Deserializer &deserializer) {
	WALCreateTrigger result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "trigger", result.trigger);
	return result;
}

void WALCreateType::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "type", type);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "type", type);
	}
}

WALCreateType WALCreateType::Deserialize(Deserializer &deserializer) {
	WALCreateType result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "type", result.type);
	return result;
}

void WALCreateView::Serialize(Serializer &serializer) const {
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<unique_ptr<CreateInfo>>(101, "view", view);
	} else {
		serializer.WriteProperty<unique_ptr<CreateInfo>>(101, "view", view);
	}
}

WALCreateView WALCreateView::Deserialize(Deserializer &deserializer) {
	WALCreateView result;
	deserializer.ReadPropertyWithDefault<unique_ptr<CreateInfo>>(101, "view", result.view);
	return result;
}

void WALDropDatabase::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<Identifier>(101, "name", name);
}

WALDropDatabase WALDropDatabase::Deserialize(Deserializer &deserializer) {
	WALDropDatabase result;
	deserializer.ReadPropertyWithDefault<Identifier>(101, "name", result.name);
	return result;
}

void WALDropForeignServer::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<Identifier>(101, "name", name);
}

WALDropForeignServer WALDropForeignServer::Deserialize(Deserializer &deserializer) {
	WALDropForeignServer result;
	deserializer.ReadPropertyWithDefault<Identifier>(101, "name", result.name);
	return result;
}

void WALDropIndex::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16484, "oid", oid, 0);
	}
}

WALDropIndex WALDropIndex::Deserialize(Deserializer &deserializer) {
	WALDropIndex result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16484, "oid", result.oid, 0);
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropMacro::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16484, "oid", oid, 0);
	}
}

WALDropMacro WALDropMacro::Deserialize(Deserializer &deserializer) {
	WALDropMacro result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16484, "oid", result.oid, 0);
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropRole::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<Identifier>(101, "name", name);
}

WALDropRole WALDropRole::Deserialize(Deserializer &deserializer) {
	WALDropRole result;
	deserializer.ReadPropertyWithDefault<Identifier>(101, "name", result.name);
	return result;
}

void WALDropSchema::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", schema);
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(102, "qualified_name", qualified_name, QualifiedName());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16484, "oid", oid, 0);
	}
}

WALDropSchema WALDropSchema::Deserialize(Deserializer &deserializer) {
	WALDropSchema result;
	deserializer.ReadPropertyWithDefault<Identifier>(101, "schema", result.schema);
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(102, "qualified_name", result.qualified_name, QualifiedName());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16484, "oid", result.oid, 0);
	return result;
}

void WALDropSequence::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16484, "oid", oid, 0);
	}
}

WALDropSequence WALDropSequence::Deserialize(Deserializer &deserializer) {
	WALDropSequence result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16484, "oid", result.oid, 0);
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropTable::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16484, "oid", oid, 0);
	}
}

WALDropTable WALDropTable::Deserialize(Deserializer &deserializer) {
	WALDropTable result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16484, "oid", result.oid, 0);
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropTableMacro::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16484, "oid", oid, 0);
	}
}

WALDropTableMacro WALDropTableMacro::Deserialize(Deserializer &deserializer) {
	WALDropTableMacro result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16484, "oid", result.oid, 0);
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropTokenizer::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<QualifiedName>(101, "qualified_name", qualified_name);
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16484, "oid", oid, 0);
	}
}

WALDropTokenizer WALDropTokenizer::Deserialize(Deserializer &deserializer) {
	WALDropTokenizer result;
	deserializer.ReadProperty<QualifiedName>(101, "qualified_name", result.qualified_name);
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16484, "oid", result.oid, 0);
	return result;
}

void WALDropTrigger::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	serializer.WritePropertyWithDefault<Identifier>(103, "table", table);
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(104, "qualified_name", qualified_name, QualifiedName());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16484, "oid", oid, 0);
	}
}

WALDropTrigger WALDropTrigger::Deserialize(Deserializer &deserializer) {
	WALDropTrigger result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithDefault<Identifier>(103, "table", result.table);
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(104, "qualified_name", result.qualified_name, QualifiedName());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16484, "oid", result.oid, 0);
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropType::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16484, "oid", oid, 0);
	}
}

WALDropType WALDropType::Deserialize(Deserializer &deserializer) {
	WALDropType result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16484, "oid", result.oid, 0);
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALDropView::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16484, "oid", oid, 0);
	}
}

WALDropView WALDropView::Deserialize(Deserializer &deserializer) {
	WALDropView result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16484, "oid", result.oid, 0);
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALPrepared::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<hugeint_t>(101, "txid", txid);
}

WALPrepared WALPrepared::Deserialize(Deserializer &deserializer) {
	WALPrepared result;
	deserializer.ReadProperty<hugeint_t>(101, "txid", result.txid);
	return result;
}

void WALSequenceValue::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "name", LegacyName());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<uint64_t>(103, "usage_count", usage_count);
	} else {
		serializer.WriteProperty<uint64_t>(103, "usage_count", usage_count);
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<int64_t>(104, "counter", counter);
	} else {
		serializer.WriteProperty<int64_t>(104, "counter", counter);
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<optional<int64_t>>(105, "last_value", last_value);
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(106, "qualified_name", qualified_name, QualifiedName());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16484, "oid", oid, 0);
	}
}

WALSequenceValue WALSequenceValue::Deserialize(Deserializer &deserializer) {
	WALSequenceValue result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto name = deserializer.ReadPropertyWithDefault<Identifier>(102, "name");
	deserializer.ReadPropertyWithDefault<uint64_t>(103, "usage_count", result.usage_count);
	deserializer.ReadPropertyWithDefault<int64_t>(104, "counter", result.counter);
	deserializer.ReadPropertyWithDefault<optional<int64_t>>(105, "last_value", result.last_value);
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(106, "qualified_name", result.qualified_name, QualifiedName());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16484, "oid", result.oid, 0);
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(name));
	}
	return result;
}

void WALUseCatalog::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<idx_t>(101, "catalog_oid", catalog_oid);
}

WALUseCatalog WALUseCatalog::Deserialize(Deserializer &deserializer) {
	WALUseCatalog result;
	deserializer.ReadPropertyWithDefault<idx_t>(101, "catalog_oid", result.catalog_oid);
	return result;
}

void WALUseTable::Serialize(Serializer &serializer) const {
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(102, "table", LegacyTable());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<QualifiedName>(103, "qualified_name", qualified_name, QualifiedName());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16484, "table_oid", table_oid, 0);
	}
}

WALUseTable WALUseTable::Deserialize(Deserializer &deserializer) {
	WALUseTable result;
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	auto table = deserializer.ReadPropertyWithDefault<Identifier>(102, "table");
	deserializer.ReadPropertyWithExplicitDefault<QualifiedName>(103, "qualified_name", result.qualified_name, QualifiedName());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16484, "table_oid", result.table_oid, 0);
	if (result.qualified_name.Path().empty()) {
		result.qualified_name = QualifiedName(vector<Identifier> {std::move(schema)}, std::move(table));
	}
	return result;
}

} // namespace duckdb
