//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_serialization.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#include "duckdb/common/serializer/serializer.hpp"
#include "duckdb/common/serializer/deserializer.hpp"
#include "duckdb/catalog/dependency.hpp"
#include "duckdb/parser/parsed_data/alter_table_info.hpp"
#include "duckdb/catalog/dependency_list.hpp"

namespace duckdb {

void CatalogEntryInfo::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<CatalogType>(100, "type", type);
	if (!serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(101, "schema", LegacySchema());
	}
	serializer.WritePropertyWithDefault<Identifier>(102, "name", name);
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<vector<Identifier>>(103, "schema_path", schema_path, vector<Identifier>());
	}
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(104, "table", table, Identifier());
	}
}

CatalogEntryInfo CatalogEntryInfo::Deserialize(Deserializer &deserializer) {
	CatalogEntryInfo result;
	deserializer.ReadProperty<CatalogType>(100, "type", result.type);
	auto schema = deserializer.ReadPropertyWithDefault<Identifier>(101, "schema");
	deserializer.ReadPropertyWithDefault<Identifier>(102, "name", result.name);
	deserializer.ReadPropertyWithExplicitDefault<vector<Identifier>>(103, "schema_path", result.schema_path, vector<Identifier>());
	deserializer.ReadPropertyWithExplicitDefault<Identifier>(104, "table", result.table, Identifier());
	if (result.schema_path.empty() && result.type != CatalogType::SCHEMA_ENTRY && !schema.empty()) {
		result.schema_path.push_back(std::move(schema));
	}
	return result;
}

void DependencyDependentFlags::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<uint8_t>(100, "value", RawValue());
}

DependencyDependentFlags DependencyDependentFlags::Deserialize(Deserializer &deserializer) {
	auto value = deserializer.ReadPropertyWithDefault<uint8_t>(100, "value");
	DependencyDependentFlags result(value);
	return result;
}

void LogicalDependency::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<CatalogEntryInfo>(100, "entry", entry);
	serializer.WritePropertyWithDefault<Identifier>(101, "catalog", catalog);
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<DependencyDependentFlags>(102, "flags", flags, DependencyDependentFlags().SetBlocking());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<bool>(16484, "owned_by", owned_by, false);
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<subdependency_set_t>(16485, "subdependencies", subdependencies, subdependency_set_t());
	}
	if (serializer.ShouldSerialize(StorageVersion::SERENEDB_V1)) {
		serializer.WritePropertyWithDefault<idx_t>(16486, "oid", oid, 0);
	}
}

LogicalDependency LogicalDependency::Deserialize(Deserializer &deserializer) {
	auto entry = deserializer.ReadProperty<CatalogEntryInfo>(100, "entry");
	auto catalog = deserializer.ReadPropertyWithDefault<Identifier>(101, "catalog");
	LogicalDependency result(deserializer.TryGet<Catalog>(), entry, std::move(catalog));
	deserializer.ReadPropertyWithExplicitDefault<DependencyDependentFlags>(102, "flags", result.flags, DependencyDependentFlags().SetBlocking());
	deserializer.ReadPropertyWithExplicitDefault<bool>(16484, "owned_by", result.owned_by, false);
	deserializer.ReadPropertyWithExplicitDefault<subdependency_set_t>(16485, "subdependencies", result.subdependencies, subdependency_set_t());
	deserializer.ReadPropertyWithExplicitDefault<idx_t>(16486, "oid", result.oid, 0);
	return result;
}

void LogicalDependencyList::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<create_info_set_t>(100, "set", set);
}

LogicalDependencyList LogicalDependencyList::Deserialize(Deserializer &deserializer) {
	LogicalDependencyList result;
	deserializer.ReadProperty<create_info_set_t>(100, "set", result.set);
	return result;
}

void SubDependency::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<AlterTableType>(100, "alter", alter);
	serializer.WritePropertyWithDefault<Identifier>(101, "name", name);
}

SubDependency SubDependency::Deserialize(Deserializer &deserializer) {
	SubDependency result;
	deserializer.ReadProperty<AlterTableType>(100, "alter", result.alter);
	deserializer.ReadPropertyWithDefault<Identifier>(101, "name", result.name);
	return result;
}

} // namespace duckdb
