//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_serialization.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#include "duckdb/common/serializer/serializer.hpp"
#include "duckdb/common/serializer/deserializer.hpp"
#include "duckdb/catalog/dependency.hpp"
#include "duckdb/parser/parsed_data/alter_table_info.hpp"
#include "duckdb/catalog/dependency_list.hpp"

namespace duckdb {

void CatalogEntryInfo::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<CatalogType>(100, "type", type);
	serializer.WritePropertyWithDefault<Identifier>(101, "schema", schema);
	serializer.WritePropertyWithDefault<Identifier>(102, "name", name);
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<Identifier>(104, "table", table, Identifier());
	}
}

CatalogEntryInfo CatalogEntryInfo::Deserialize(Deserializer &deserializer) {
	CatalogEntryInfo result;
	deserializer.ReadProperty<CatalogType>(100, "type", result.type);
	deserializer.ReadPropertyWithDefault<Identifier>(101, "schema", result.schema);
	deserializer.ReadPropertyWithDefault<Identifier>(102, "name", result.name);
	deserializer.ReadPropertyWithExplicitDefault<Identifier>(104, "table", result.table, Identifier());
	return result;
}

void DependencyDependentFlags::Serialize(Serializer &serializer) const {
	serializer.WritePropertyWithDefault<uint8_t>(100, "value", RawValue());
}

DependencyDependentFlags DependencyDependentFlags::Deserialize(Deserializer &deserializer) {
	auto value = deserializer.ReadPropertyWithDefault<uint8_t>(100, "value");
	DependencyDependentFlags result(value);
	return result;
}

void LogicalDependency::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<CatalogEntryInfo>(100, "entry", entry);
	serializer.WritePropertyWithDefault<Identifier>(101, "catalog", catalog);
	serializer.WritePropertyWithDefault<bool>(102, "owned_by", owned_by, false);
	serializer.WritePropertyWithDefault<subdependency_set_t>(103, "subdependencies", subdependencies, subdependency_set_t());
	if (serializer.ShouldSerialize(StorageVersion::V2_0_0)) {
		serializer.WritePropertyWithDefault<DependencyDependentFlags>(104, "flags", flags, DependencyDependentFlags().SetBlocking());
	}
}

LogicalDependency LogicalDependency::Deserialize(Deserializer &deserializer) {
	auto entry = deserializer.ReadProperty<CatalogEntryInfo>(100, "entry");
	auto catalog = deserializer.ReadPropertyWithDefault<Identifier>(101, "catalog");
	LogicalDependency result(deserializer.TryGet<Catalog>(), entry, std::move(catalog));
	deserializer.ReadPropertyWithExplicitDefault<bool>(102, "owned_by", result.owned_by, false);
	deserializer.ReadPropertyWithExplicitDefault<subdependency_set_t>(103, "subdependencies", result.subdependencies, subdependency_set_t());
	deserializer.ReadPropertyWithExplicitDefault<DependencyDependentFlags>(104, "flags", result.flags, DependencyDependentFlags().SetBlocking());
	return result;
}

void LogicalDependencyList::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<create_info_set_t>(100, "set", set);
}

LogicalDependencyList LogicalDependencyList::Deserialize(Deserializer &deserializer) {
	LogicalDependencyList result;
	deserializer.ReadProperty<create_info_set_t>(100, "set", result.set);
	return result;
}

void SubDependency::Serialize(Serializer &serializer) const {
	serializer.WriteProperty<AlterTableType>(100, "alter", alter);
	serializer.WritePropertyWithDefault<Identifier>(101, "name", name);
}

SubDependency SubDependency::Deserialize(Deserializer &deserializer) {
	SubDependency result;
	deserializer.ReadProperty<AlterTableType>(100, "alter", result.alter);
	deserializer.ReadPropertyWithDefault<Identifier>(101, "name", result.name);
	return result;
}

} // namespace duckdb
