//-------------------------------------------------------------------------
// This file is automatically generated by scripts/generate_enum_util.py
// Do not edit this file manually, your changes will be overwritten
// If you want to exclude an enum from serialization, add it to the blacklist in the script
//
// Note: The generated code will only work properly if the enum is a top level item in the duckdb namespace
// If the enum is nested in a class, or in another namespace, the generated code will not compile.
// You should move the enum to the duckdb namespace, manually write a specialization or add it to the blacklist
//-------------------------------------------------------------------------


#pragma once

#include <stdint.h>
#include <string_view>
#include "duckdb/common/string.hpp"

namespace duckdb {

struct EnumUtil {
    // String -> Enum
    template <class T>
    static T FromString(std::string_view value) = delete;

    // Enum -> String
    template <class T>
    static const char *ToChars(T value) = delete;

    template <class T>
    static string ToString(T value) { return string(ToChars<T>(value)); }
};

enum class ARTConflictType : uint8_t;

enum class ARTScanNodeResult : uint8_t;

enum class ARTScanProgress : uint8_t;

enum class ARTSearchResult : uint8_t;

enum class AccessMode : uint8_t;

enum class AclMode : uint64_t;

enum class AdaptiveFilterSource : uint8_t;

enum class AggregateCombineType : uint8_t;

enum class AggregateDistinctDependent : uint8_t;

enum class AggregateHandling : uint8_t;

enum class AggregateOrderDependent : uint8_t;

enum class AggregateRewritePolicy : uint8_t;

enum class AggregateRewriteSourceType : uint8_t;

enum class AggregateStateExportMode : uint8_t;

enum class AggregateType : uint8_t;

enum class AlterDatabaseType : uint8_t;

enum class AlterForeignKeyType : uint8_t;

enum class AlterIndexType : uint8_t;

enum class AlterScalarFunctionType : uint8_t;

enum class AlterSchemaType : uint8_t;

enum class AlterSequenceType : uint8_t;

enum class AlterTableFunctionType : uint8_t;

enum class AlterTableType : uint8_t;

enum class AlterType : uint8_t;

enum class AlterViewType : uint8_t;

enum class AppenderType : uint8_t;

enum class ArrowArrayPhysicalType : uint8_t;

enum class ArrowDateTimeType : uint8_t;

enum class ArrowFormatVersion : uint8_t;

enum class ArrowOffsetSize : uint8_t;

enum class ArrowTypeInfoType : uint8_t;

enum class ArrowVariableSizeType : uint8_t;

enum class AsyncResultType : uint8_t;

enum class AsyncResultsExecutionMode : uint8_t;

enum class BaseColumnPrunerMode : uint8_t;

enum class BinderType : uint8_t;

enum class BindingMode : uint8_t;

enum class BitpackingMode : uint8_t;

enum class BlockIteratorStateType : int8_t;

enum class BlockState : uint8_t;

enum class BufferedIndexReplay : uint8_t;

enum class CAPIResultSetType : uint8_t;

enum class CSVState : uint8_t;

enum class CTEExecutionMode : uint8_t;

enum class CTEMaterialize : uint8_t;

enum class CacheBlockState : uint8_t;

enum class CacheValidationMode : uint8_t;

enum class CachingMode : uint8_t;

enum class CanUnloadResult : uint8_t;

enum class CatalogLookupBehavior : uint8_t;

enum class CatalogType : uint8_t;

enum class CheckpointAbort : uint8_t;

enum class CheckpointOnDetach : uint8_t;

enum class ChunkInfoType : uint8_t;

enum class ClientInterruptState : uint8_t;

enum class ColumnDataAllocatorType : uint8_t;

enum class ColumnDataScanProperties : uint8_t;

enum class ColumnIndexType : uint8_t;

enum class ColumnSegmentType : uint8_t;

enum class CompressedMaterializationDirection : uint8_t;

enum class CompressedMaterializationType : uint8_t;

enum class CompressionType : uint8_t;

enum class CompressionValidity : uint8_t;

enum class ConflictManagerMode : uint8_t;

enum class ConstraintCheckMode : uint8_t;

enum class ConstraintType : uint8_t;

enum class CoordinateReferenceSystemType : uint8_t;

enum class CopyFunctionFlushBatchReason : uint8_t;

enum class CopyFunctionReturnType : uint8_t;

enum class CopyOverwriteMode : uint8_t;

enum class CopyToType : uint8_t;

enum class CryptoHashFunction : uint8_t;

enum class DataFileType : uint8_t;

enum class DateCastResult : uint8_t;

enum class DatePartSpecifier : uint8_t;

enum class DebugInitialize : uint8_t;

enum class DebugOrderVerification : uint8_t;

enum class DebugProgressVerification : uint8_t;

enum class DebugStatementVerification : uint8_t;

enum class DebugVectorVerification : uint8_t;

enum class DebugVerificationMode : uint8_t;

enum class DecimalBitWidth : uint8_t;

enum class DefaultOrderByNullType : uint8_t;

enum class DeferredRuntimeFilterType : uint8_t;

enum class DeleteIdState : uint8_t;

enum class DependencyEntryType : uint8_t;

enum class DeprecatedIndexType : uint8_t;

enum class DestroyBufferUpon : uint8_t;

enum class DialectCompatibilityMode : uint8_t;

enum class DictFSSTMode : uint8_t;

enum class DistinctCountSource : uint8_t;

enum class DistinctType : uint8_t;

enum class ErrorType : uint16_t;

enum class ExceptionFormatValueType : uint8_t;

enum class ExceptionType : uint8_t;

enum class ExplainFormatShape : uint8_t;

enum class ExplainOutputType : uint8_t;

enum class ExplainType : uint8_t;

enum class ExponentType : uint8_t;

enum class ExpressionClass : uint8_t;

enum class ExpressionTailType : uint8_t;

enum class ExpressionType : uint8_t;

enum class ExtensionABIType : uint8_t;

enum class ExtensionInstallMode : uint8_t;

enum class ExtensionLoadResult : uint8_t;

enum class ExtensionRepositoryAccess : uint8_t;

enum class ExtensionRepositoryType : uint8_t;

enum class ExtensionUpdateResultTag : uint8_t;

enum class ExternalResourceOperation : uint8_t;

enum class ExtraDropInfoType : uint8_t;

enum class ExtraPersistentColumnDataType : uint8_t;

enum class FileBufferType : uint8_t;

enum class FileExpandResult : uint8_t;

enum class FileGlobOptions : uint8_t;

enum class FileIOMode : uint8_t;

enum class FileLockType : uint8_t;

enum class FileNameSegmentType : uint8_t;

enum class FileSyncMode : uint8_t;

enum class FileSyncParallelism : uint8_t;

enum class FileWriteMode : uint8_t;

enum class FilterPropagateResult : uint8_t;

enum class FilterReorder : uint8_t;

enum class ForeignKeyType : uint8_t;

enum class FormatArgumentType : uint8_t;

enum class FunctionCollationHandling : uint8_t;

enum class FunctionErrors : uint8_t;

enum class FunctionNullHandling : uint8_t;

enum class FunctionParameterKind : uint8_t;

enum class FunctionStability : uint8_t;

enum class GateStatus : uint8_t;

enum class GeometryStorageType : uint8_t;

enum class GeometryType : uint8_t;

enum class GroupByExpressionInfoType : uint8_t;

enum class HLLStorageType : uint8_t;

enum class HTTPClientCachePolicy : uint8_t;

enum class HTTPStatusCode : uint16_t;

enum class HTTPTransportReusePolicy : uint8_t;

enum class IdentifierCaseMode : uint8_t;

enum class IndexAppendMode : uint8_t;

enum class IndexBindState : uint8_t;

enum class IndexConstraintType : uint8_t;

enum class IndexDeltaType : uint8_t;

enum class InsertColumnOrder : uint8_t;

enum class InterruptMode : uint8_t;

enum class JoinFilterPushdownMode : uint8_t;

enum class JoinOrderOperatorType : uint8_t;

enum class JoinRefType : uint8_t;

enum class JoinType : uint8_t;

enum class KeywordCase : uint8_t;

enum class KeywordCategory : uint8_t;

enum class LambdaSyntax : uint8_t;

enum class LambdaSyntaxType : uint8_t;

enum class LimitNodeType : uint8_t;

enum class LimitValueType : uint8_t;

enum class LiteralKind : uint8_t;

enum class LoadType : uint8_t;

enum class LogContextScope : uint8_t;

enum class LogLevel : uint8_t;

enum class LogMode : uint8_t;

enum class LoggingTargetTable : uint8_t;

enum class LogicalOperatorRepeatability : uint8_t;

enum class LogicalOperatorType : uint8_t;

enum class LogicalPlanVerificationIssueCode : int32_t;

enum class LogicalPlanVerificationPathComponentType : int32_t;

enum class LogicalPlanVerificationPhase : int32_t;

enum class LogicalTypeId : uint8_t;

enum class LogicalTypeInfoType : uint8_t;

enum class LookupResultType : uint8_t;

enum class MacroType : uint8_t;

enum class MapInvalidReason : uint8_t;

enum class MatchMode : uint8_t;

enum class MatchRecognizeAfterMatch : uint8_t;

enum class MatchRecognizeClauseKind : uint8_t;

enum class MatchRecognizePatternType : uint8_t;

enum class MatchRecognizeRows : uint8_t;

enum class MemoryTag : uint8_t;

enum class MergeActionCondition : uint8_t;

enum class MergeActionType : uint8_t;

enum class MetaPipelineType : uint8_t;

enum class Monotonicity : uint8_t;

enum class MultiFileClaimResult : uint8_t;

enum class MultiFileColumnMappingMode : uint8_t;

enum class MultiFileDecodeResult : uint8_t;

enum class MultiFileFileState : uint8_t;

enum class MultiFileJobState : uint8_t;

enum class NType : uint8_t;

enum class NewLineIdentifier : uint8_t;

enum class OnConflictAction : uint8_t;

enum class OnCreateConflict : uint8_t;

enum class OnEntryNotFound : uint8_t;

enum class OperatorCachingMode : uint8_t;

enum class OperatorFinalResultType : uint8_t;

enum class OperatorFinalizeResultType : uint8_t;

enum class OperatorMatcherMode : uint8_t;

enum class OperatorResultType : uint8_t;

enum class OptimizerHookPosition : uint8_t;

enum class OptimizerType : uint32_t;

enum class OrderByColumnType : uint8_t;

enum class OrderByNullType : uint8_t;

enum class OrderByStatistics : uint8_t;

enum class OrderPreservationType : uint8_t;

enum class OrderType : uint8_t;

enum class OrdinalityType : uint8_t;

enum class OutputStream : uint8_t;

enum class ParseInfoType : uint8_t;

enum class ParseResultType : uint8_t;

enum class PartitionedColumnDataType : uint8_t;

enum class PartitionedTupleDataType : uint8_t;

enum class PatternMatchType : uint8_t;

enum class PatternMemo : uint8_t;

enum class PatternOp : uint8_t;

enum class PhysicalOperatorType : uint8_t;

enum class PhysicalTableScanExecutionStrategy : uint8_t;

enum class PhysicalType : uint8_t;

enum class PipelineBroadcastExchangeConsumerMode : uint8_t;

enum class PipelineBroadcastExchangeOrderMode : uint8_t;

enum class PipelineBroadcastExchangeScanMode : uint8_t;

enum class PipelineInputMode : uint8_t;

enum class PipelineScheduleMode : uint8_t;

enum class PipelineScheduleStageType : uint8_t;

enum class PragmaType : uint8_t;

enum class PreparedParamType : uint8_t;

enum class PreparedStatementMode : uint8_t;

enum class PreserveOrderType : uint8_t;

enum class ProfilingCoverage : uint8_t;

enum class ProfilingParameterNames : uint8_t;

enum class ProgressInvariant : uint8_t;

enum class PushdownExtractSupport : uint8_t;

enum class QualifiedNameToStringMode : uint8_t;

enum class QuantileSerializationType : uint8_t;

enum class QueryNodeType : uint8_t;

enum class QueryResultMemoryType : uint8_t;

enum class QueryResultState : uint8_t;

enum class RecoveryMode : uint8_t;

enum class RecursiveCTEPipelineMetricType : uint8_t;

enum class RecursiveCTESourcePhase : uint8_t;

enum class RecursiveProbeSidePreference : uint8_t;

enum class RegexMatchOperatorSemantics : uint8_t;

enum class RelationType : uint8_t;

enum class RemoteCapability : uint8_t;

enum class RemoveUnusedColumnsMode : uint8_t;

enum class RenderMode : uint8_t;

enum class RequestSizing : uint8_t;

enum class RequestType : uint8_t;

enum class ResultEagerness : uint8_t;

enum class ResultLifetime : uint8_t;

enum class ResultModifierType : uint8_t;

enum class ResultOrdering : uint8_t;

enum class RoleOption : uint32_t;

enum class RowGroupAppendMode : uint8_t;

enum class RowIdHandling : uint8_t;

enum class SampleMethod : uint8_t;

enum class SampleType : uint8_t;

enum class SamplingState : uint8_t;

enum class ScanReadAheadAcquire : uint8_t;

enum class ScanType : uint8_t;

enum class SecretDisplayType : uint8_t;

enum class SecretPersistType : uint8_t;

enum class SecretSerializationType : uint8_t;

enum class SegmentTreeVerifyMode : uint8_t;

enum class SelectivityOptionalFilterType : uint8_t;

enum class SequenceInfo : uint8_t;

enum class SerializationVersionDeprecated : uint64_t;

enum class SetOperationType : uint8_t;

enum class SetScope : uint8_t;

enum class SetType : uint8_t;

enum class SettingScope : uint8_t;

enum class ShowBehaviorType : uint8_t;

enum class ShowType : uint8_t;

enum class SimplifiedTokenType : uint8_t;

enum class SinkCombineResultType : uint8_t;

enum class SinkFinalizeType : uint8_t;

enum class SinkNextBatchType : uint8_t;

enum class SinkResultType : uint8_t;

enum class SortKeyType : uint8_t;

enum class SourceBatchIndexState : uint8_t;

enum class SourceResultType : uint8_t;

enum class SqlCompatibility : uint8_t;

enum class StarExpressionType : uint8_t;

enum class StateMemoryOwnership : uint8_t;

enum class StatementReturnType : uint8_t;

enum class StatementType : uint8_t;

enum class StatisticsPropagationMode : uint8_t;

enum class StatisticsType : uint8_t;

enum class StatsInfo : uint8_t;

enum class StorageBlockPrefetch : uint8_t;

enum class StorageIndexType : uint8_t;

enum class StrTimeSpecifier : uint8_t;

enum class SubqueryType : uint8_t;

enum class SuggestionState : uint8_t;

enum class TableColumnType : uint8_t;

enum class TableFilterPushdown : uint8_t;

enum class TableFilterType : uint8_t;

enum class TableFunctionIdentifierConversion : uint8_t;

enum class TableFunctionParallelism : uint8_t;

enum class TablePartitionInfo : uint8_t;

enum class TableReferenceType : uint8_t;

enum class TaskExecutionMode : uint8_t;

enum class TaskExecutionResult : uint8_t;

enum class TaskSchedulerType : uint8_t;

enum class TemporaryBufferSize : uint64_t;

enum class TemporaryCompressionLevel : int;

enum class ThreadPinMode : uint8_t;

enum class TimestampCastResult : uint8_t;

enum class TokenType : uint8_t;

enum class TransactionInvalidationPolicy : uint8_t;

enum class TransactionIsolationLevel : uint8_t;

enum class TransactionModifierType : uint8_t;

enum class TransactionType : uint8_t;

enum class TriggerEventType : uint8_t;

enum class TriggerForEach : uint8_t;

enum class TriggerTiming : uint8_t;

enum class TupleDataNestednessType : uint8_t;

enum class TupleDataPinProperties : uint8_t;

enum class TupleDataValidityType : uint8_t;

enum class UndoFlags : uint32_t;

enum class UnionInvalidReason : uint8_t;

enum class VacuumIndexStrategy : uint8_t;

enum class VariantChildLookupMode : uint8_t;

enum class VariantComparisonType : uint8_t;

enum class VariantLogicalType : uint8_t;

enum class VariantStatsShreddingState : uint8_t;

enum class VectorBufferType : uint8_t;

enum class VectorPrepareState : uint8_t;

enum class VectorType : uint8_t;

enum class VerifyExistenceType : uint8_t;

enum class VersionCompressionResult : uint8_t;

enum class VertexType : uint8_t;

enum class ViewSecurityType : uint8_t;

enum class WALType : uint8_t;

enum class WindowAggregationMode : uint32_t;

enum class WindowBoundary : uint8_t;

enum class WindowExcludeMode : uint8_t;

enum class WindowMergeSortStage : uint8_t;


template<>
const char* EnumUtil::ToChars<ARTConflictType>(ARTConflictType value);

template<>
const char* EnumUtil::ToChars<ARTScanNodeResult>(ARTScanNodeResult value);

template<>
const char* EnumUtil::ToChars<ARTScanProgress>(ARTScanProgress value);

template<>
const char* EnumUtil::ToChars<ARTSearchResult>(ARTSearchResult value);

template<>
const char* EnumUtil::ToChars<AccessMode>(AccessMode value);

template<>
const char* EnumUtil::ToChars<AclMode>(AclMode value);

template<>
const char* EnumUtil::ToChars<AdaptiveFilterSource>(AdaptiveFilterSource value);

template<>
const char* EnumUtil::ToChars<AggregateCombineType>(AggregateCombineType value);

template<>
const char* EnumUtil::ToChars<AggregateDistinctDependent>(AggregateDistinctDependent value);

template<>
const char* EnumUtil::ToChars<AggregateHandling>(AggregateHandling value);

template<>
const char* EnumUtil::ToChars<AggregateOrderDependent>(AggregateOrderDependent value);

template<>
const char* EnumUtil::ToChars<AggregateRewritePolicy>(AggregateRewritePolicy value);

template<>
const char* EnumUtil::ToChars<AggregateRewriteSourceType>(AggregateRewriteSourceType value);

template<>
const char* EnumUtil::ToChars<AggregateStateExportMode>(AggregateStateExportMode value);

template<>
const char* EnumUtil::ToChars<AggregateType>(AggregateType value);

template<>
const char* EnumUtil::ToChars<AlterDatabaseType>(AlterDatabaseType value);

template<>
const char* EnumUtil::ToChars<AlterForeignKeyType>(AlterForeignKeyType value);

template<>
const char* EnumUtil::ToChars<AlterIndexType>(AlterIndexType value);

template<>
const char* EnumUtil::ToChars<AlterScalarFunctionType>(AlterScalarFunctionType value);

template<>
const char* EnumUtil::ToChars<AlterSchemaType>(AlterSchemaType value);

template<>
const char* EnumUtil::ToChars<AlterSequenceType>(AlterSequenceType value);

template<>
const char* EnumUtil::ToChars<AlterTableFunctionType>(AlterTableFunctionType value);

template<>
const char* EnumUtil::ToChars<AlterTableType>(AlterTableType value);

template<>
const char* EnumUtil::ToChars<AlterType>(AlterType value);

template<>
const char* EnumUtil::ToChars<AlterViewType>(AlterViewType value);

template<>
const char* EnumUtil::ToChars<AppenderType>(AppenderType value);

template<>
const char* EnumUtil::ToChars<ArrowArrayPhysicalType>(ArrowArrayPhysicalType value);

template<>
const char* EnumUtil::ToChars<ArrowDateTimeType>(ArrowDateTimeType value);

template<>
const char* EnumUtil::ToChars<ArrowFormatVersion>(ArrowFormatVersion value);

template<>
const char* EnumUtil::ToChars<ArrowOffsetSize>(ArrowOffsetSize value);

template<>
const char* EnumUtil::ToChars<ArrowTypeInfoType>(ArrowTypeInfoType value);

template<>
const char* EnumUtil::ToChars<ArrowVariableSizeType>(ArrowVariableSizeType value);

template<>
const char* EnumUtil::ToChars<AsyncResultType>(AsyncResultType value);

template<>
const char* EnumUtil::ToChars<AsyncResultsExecutionMode>(AsyncResultsExecutionMode value);

template<>
const char* EnumUtil::ToChars<BaseColumnPrunerMode>(BaseColumnPrunerMode value);

template<>
const char* EnumUtil::ToChars<BinderType>(BinderType value);

template<>
const char* EnumUtil::ToChars<BindingMode>(BindingMode value);

template<>
const char* EnumUtil::ToChars<BitpackingMode>(BitpackingMode value);

template<>
const char* EnumUtil::ToChars<BlockIteratorStateType>(BlockIteratorStateType value);

template<>
const char* EnumUtil::ToChars<BlockState>(BlockState value);

template<>
const char* EnumUtil::ToChars<BufferedIndexReplay>(BufferedIndexReplay value);

template<>
const char* EnumUtil::ToChars<CAPIResultSetType>(CAPIResultSetType value);

template<>
const char* EnumUtil::ToChars<CSVState>(CSVState value);

template<>
const char* EnumUtil::ToChars<CTEExecutionMode>(CTEExecutionMode value);

template<>
const char* EnumUtil::ToChars<CTEMaterialize>(CTEMaterialize value);

template<>
const char* EnumUtil::ToChars<CacheBlockState>(CacheBlockState value);

template<>
const char* EnumUtil::ToChars<CacheValidationMode>(CacheValidationMode value);

template<>
const char* EnumUtil::ToChars<CachingMode>(CachingMode value);

template<>
const char* EnumUtil::ToChars<CanUnloadResult>(CanUnloadResult value);

template<>
const char* EnumUtil::ToChars<CatalogLookupBehavior>(CatalogLookupBehavior value);

template<>
const char* EnumUtil::ToChars<CatalogType>(CatalogType value);

template<>
const char* EnumUtil::ToChars<CheckpointAbort>(CheckpointAbort value);

template<>
const char* EnumUtil::ToChars<CheckpointOnDetach>(CheckpointOnDetach value);

template<>
const char* EnumUtil::ToChars<ChunkInfoType>(ChunkInfoType value);

template<>
const char* EnumUtil::ToChars<ClientInterruptState>(ClientInterruptState value);

template<>
const char* EnumUtil::ToChars<ColumnDataAllocatorType>(ColumnDataAllocatorType value);

template<>
const char* EnumUtil::ToChars<ColumnDataScanProperties>(ColumnDataScanProperties value);

template<>
const char* EnumUtil::ToChars<ColumnIndexType>(ColumnIndexType value);

template<>
const char* EnumUtil::ToChars<ColumnSegmentType>(ColumnSegmentType value);

template<>
const char* EnumUtil::ToChars<CompressedMaterializationDirection>(CompressedMaterializationDirection value);

template<>
const char* EnumUtil::ToChars<CompressedMaterializationType>(CompressedMaterializationType value);

template<>
const char* EnumUtil::ToChars<CompressionType>(CompressionType value);

template<>
const char* EnumUtil::ToChars<CompressionValidity>(CompressionValidity value);

template<>
const char* EnumUtil::ToChars<ConflictManagerMode>(ConflictManagerMode value);

template<>
const char* EnumUtil::ToChars<ConstraintCheckMode>(ConstraintCheckMode value);

template<>
const char* EnumUtil::ToChars<ConstraintType>(ConstraintType value);

template<>
const char* EnumUtil::ToChars<CoordinateReferenceSystemType>(CoordinateReferenceSystemType value);

template<>
const char* EnumUtil::ToChars<CopyFunctionFlushBatchReason>(CopyFunctionFlushBatchReason value);

template<>
const char* EnumUtil::ToChars<CopyFunctionReturnType>(CopyFunctionReturnType value);

template<>
const char* EnumUtil::ToChars<CopyOverwriteMode>(CopyOverwriteMode value);

template<>
const char* EnumUtil::ToChars<CopyToType>(CopyToType value);

template<>
const char* EnumUtil::ToChars<CryptoHashFunction>(CryptoHashFunction value);

template<>
const char* EnumUtil::ToChars<DataFileType>(DataFileType value);

template<>
const char* EnumUtil::ToChars<DateCastResult>(DateCastResult value);

template<>
const char* EnumUtil::ToChars<DatePartSpecifier>(DatePartSpecifier value);

template<>
const char* EnumUtil::ToChars<DebugInitialize>(DebugInitialize value);

template<>
const char* EnumUtil::ToChars<DebugOrderVerification>(DebugOrderVerification value);

template<>
const char* EnumUtil::ToChars<DebugProgressVerification>(DebugProgressVerification value);

template<>
const char* EnumUtil::ToChars<DebugStatementVerification>(DebugStatementVerification value);

template<>
const char* EnumUtil::ToChars<DebugVectorVerification>(DebugVectorVerification value);

template<>
const char* EnumUtil::ToChars<DebugVerificationMode>(DebugVerificationMode value);

template<>
const char* EnumUtil::ToChars<DecimalBitWidth>(DecimalBitWidth value);

template<>
const char* EnumUtil::ToChars<DefaultOrderByNullType>(DefaultOrderByNullType value);

template<>
const char* EnumUtil::ToChars<DeferredRuntimeFilterType>(DeferredRuntimeFilterType value);

template<>
const char* EnumUtil::ToChars<DeleteIdState>(DeleteIdState value);

template<>
const char* EnumUtil::ToChars<DependencyEntryType>(DependencyEntryType value);

template<>
const char* EnumUtil::ToChars<DeprecatedIndexType>(DeprecatedIndexType value);

template<>
const char* EnumUtil::ToChars<DestroyBufferUpon>(DestroyBufferUpon value);

template<>
const char* EnumUtil::ToChars<DialectCompatibilityMode>(DialectCompatibilityMode value);

template<>
const char* EnumUtil::ToChars<DictFSSTMode>(DictFSSTMode value);

template<>
const char* EnumUtil::ToChars<DistinctCountSource>(DistinctCountSource value);

template<>
const char* EnumUtil::ToChars<DistinctType>(DistinctType value);

template<>
const char* EnumUtil::ToChars<ErrorType>(ErrorType value);

template<>
const char* EnumUtil::ToChars<ExceptionFormatValueType>(ExceptionFormatValueType value);

template<>
const char* EnumUtil::ToChars<ExceptionType>(ExceptionType value);

template<>
const char* EnumUtil::ToChars<ExplainFormatShape>(ExplainFormatShape value);

template<>
const char* EnumUtil::ToChars<ExplainOutputType>(ExplainOutputType value);

template<>
const char* EnumUtil::ToChars<ExplainType>(ExplainType value);

template<>
const char* EnumUtil::ToChars<ExponentType>(ExponentType value);

template<>
const char* EnumUtil::ToChars<ExpressionClass>(ExpressionClass value);

template<>
const char* EnumUtil::ToChars<ExpressionTailType>(ExpressionTailType value);

template<>
const char* EnumUtil::ToChars<ExpressionType>(ExpressionType value);

template<>
const char* EnumUtil::ToChars<ExtensionABIType>(ExtensionABIType value);

template<>
const char* EnumUtil::ToChars<ExtensionInstallMode>(ExtensionInstallMode value);

template<>
const char* EnumUtil::ToChars<ExtensionLoadResult>(ExtensionLoadResult value);

template<>
const char* EnumUtil::ToChars<ExtensionRepositoryAccess>(ExtensionRepositoryAccess value);

template<>
const char* EnumUtil::ToChars<ExtensionRepositoryType>(ExtensionRepositoryType value);

template<>
const char* EnumUtil::ToChars<ExtensionUpdateResultTag>(ExtensionUpdateResultTag value);

template<>
const char* EnumUtil::ToChars<ExternalResourceOperation>(ExternalResourceOperation value);

template<>
const char* EnumUtil::ToChars<ExtraDropInfoType>(ExtraDropInfoType value);

template<>
const char* EnumUtil::ToChars<ExtraPersistentColumnDataType>(ExtraPersistentColumnDataType value);

template<>
const char* EnumUtil::ToChars<FileBufferType>(FileBufferType value);

template<>
const char* EnumUtil::ToChars<FileExpandResult>(FileExpandResult value);

template<>
const char* EnumUtil::ToChars<FileGlobOptions>(FileGlobOptions value);

template<>
const char* EnumUtil::ToChars<FileIOMode>(FileIOMode value);

template<>
const char* EnumUtil::ToChars<FileLockType>(FileLockType value);

template<>
const char* EnumUtil::ToChars<FileNameSegmentType>(FileNameSegmentType value);

template<>
const char* EnumUtil::ToChars<FileSyncMode>(FileSyncMode value);

template<>
const char* EnumUtil::ToChars<FileSyncParallelism>(FileSyncParallelism value);

template<>
const char* EnumUtil::ToChars<FileWriteMode>(FileWriteMode value);

template<>
const char* EnumUtil::ToChars<FilterPropagateResult>(FilterPropagateResult value);

template<>
const char* EnumUtil::ToChars<FilterReorder>(FilterReorder value);

template<>
const char* EnumUtil::ToChars<ForeignKeyType>(ForeignKeyType value);

template<>
const char* EnumUtil::ToChars<FormatArgumentType>(FormatArgumentType value);

template<>
const char* EnumUtil::ToChars<FunctionCollationHandling>(FunctionCollationHandling value);

template<>
const char* EnumUtil::ToChars<FunctionErrors>(FunctionErrors value);

template<>
const char* EnumUtil::ToChars<FunctionNullHandling>(FunctionNullHandling value);

template<>
const char* EnumUtil::ToChars<FunctionParameterKind>(FunctionParameterKind value);

template<>
const char* EnumUtil::ToChars<FunctionStability>(FunctionStability value);

template<>
const char* EnumUtil::ToChars<GateStatus>(GateStatus value);

template<>
const char* EnumUtil::ToChars<GeometryStorageType>(GeometryStorageType value);

template<>
const char* EnumUtil::ToChars<GeometryType>(GeometryType value);

template<>
const char* EnumUtil::ToChars<GroupByExpressionInfoType>(GroupByExpressionInfoType value);

template<>
const char* EnumUtil::ToChars<HLLStorageType>(HLLStorageType value);

template<>
const char* EnumUtil::ToChars<HTTPClientCachePolicy>(HTTPClientCachePolicy value);

template<>
const char* EnumUtil::ToChars<HTTPStatusCode>(HTTPStatusCode value);

template<>
const char* EnumUtil::ToChars<HTTPTransportReusePolicy>(HTTPTransportReusePolicy value);

template<>
const char* EnumUtil::ToChars<IdentifierCaseMode>(IdentifierCaseMode value);

template<>
const char* EnumUtil::ToChars<IndexAppendMode>(IndexAppendMode value);

template<>
const char* EnumUtil::ToChars<IndexBindState>(IndexBindState value);

template<>
const char* EnumUtil::ToChars<IndexConstraintType>(IndexConstraintType value);

template<>
const char* EnumUtil::ToChars<IndexDeltaType>(IndexDeltaType value);

template<>
const char* EnumUtil::ToChars<InsertColumnOrder>(InsertColumnOrder value);

template<>
const char* EnumUtil::ToChars<InterruptMode>(InterruptMode value);

template<>
const char* EnumUtil::ToChars<JoinFilterPushdownMode>(JoinFilterPushdownMode value);

template<>
const char* EnumUtil::ToChars<JoinOrderOperatorType>(JoinOrderOperatorType value);

template<>
const char* EnumUtil::ToChars<JoinRefType>(JoinRefType value);

template<>
const char* EnumUtil::ToChars<JoinType>(JoinType value);

template<>
const char* EnumUtil::ToChars<KeywordCase>(KeywordCase value);

template<>
const char* EnumUtil::ToChars<KeywordCategory>(KeywordCategory value);

template<>
const char* EnumUtil::ToChars<LambdaSyntax>(LambdaSyntax value);

template<>
const char* EnumUtil::ToChars<LambdaSyntaxType>(LambdaSyntaxType value);

template<>
const char* EnumUtil::ToChars<LimitNodeType>(LimitNodeType value);

template<>
const char* EnumUtil::ToChars<LimitValueType>(LimitValueType value);

template<>
const char* EnumUtil::ToChars<LiteralKind>(LiteralKind value);

template<>
const char* EnumUtil::ToChars<LoadType>(LoadType value);

template<>
const char* EnumUtil::ToChars<LogContextScope>(LogContextScope value);

template<>
const char* EnumUtil::ToChars<LogLevel>(LogLevel value);

template<>
const char* EnumUtil::ToChars<LogMode>(LogMode value);

template<>
const char* EnumUtil::ToChars<LoggingTargetTable>(LoggingTargetTable value);

template<>
const char* EnumUtil::ToChars<LogicalOperatorRepeatability>(LogicalOperatorRepeatability value);

template<>
const char* EnumUtil::ToChars<LogicalOperatorType>(LogicalOperatorType value);

template<>
const char* EnumUtil::ToChars<LogicalPlanVerificationIssueCode>(LogicalPlanVerificationIssueCode value);

template<>
const char* EnumUtil::ToChars<LogicalPlanVerificationPathComponentType>(LogicalPlanVerificationPathComponentType value);

template<>
const char* EnumUtil::ToChars<LogicalPlanVerificationPhase>(LogicalPlanVerificationPhase value);

template<>
const char* EnumUtil::ToChars<LogicalTypeId>(LogicalTypeId value);

template<>
const char* EnumUtil::ToChars<LogicalTypeInfoType>(LogicalTypeInfoType value);

template<>
const char* EnumUtil::ToChars<LookupResultType>(LookupResultType value);

template<>
const char* EnumUtil::ToChars<MacroType>(MacroType value);

template<>
const char* EnumUtil::ToChars<MapInvalidReason>(MapInvalidReason value);

template<>
const char* EnumUtil::ToChars<MatchMode>(MatchMode value);

template<>
const char* EnumUtil::ToChars<MatchRecognizeAfterMatch>(MatchRecognizeAfterMatch value);

template<>
const char* EnumUtil::ToChars<MatchRecognizeClauseKind>(MatchRecognizeClauseKind value);

template<>
const char* EnumUtil::ToChars<MatchRecognizePatternType>(MatchRecognizePatternType value);

template<>
const char* EnumUtil::ToChars<MatchRecognizeRows>(MatchRecognizeRows value);

template<>
const char* EnumUtil::ToChars<MemoryTag>(MemoryTag value);

template<>
const char* EnumUtil::ToChars<MergeActionCondition>(MergeActionCondition value);

template<>
const char* EnumUtil::ToChars<MergeActionType>(MergeActionType value);

template<>
const char* EnumUtil::ToChars<MetaPipelineType>(MetaPipelineType value);

template<>
const char* EnumUtil::ToChars<Monotonicity>(Monotonicity value);

template<>
const char* EnumUtil::ToChars<MultiFileClaimResult>(MultiFileClaimResult value);

template<>
const char* EnumUtil::ToChars<MultiFileColumnMappingMode>(MultiFileColumnMappingMode value);

template<>
const char* EnumUtil::ToChars<MultiFileDecodeResult>(MultiFileDecodeResult value);

template<>
const char* EnumUtil::ToChars<MultiFileFileState>(MultiFileFileState value);

template<>
const char* EnumUtil::ToChars<MultiFileJobState>(MultiFileJobState value);

template<>
const char* EnumUtil::ToChars<NType>(NType value);

template<>
const char* EnumUtil::ToChars<NewLineIdentifier>(NewLineIdentifier value);

template<>
const char* EnumUtil::ToChars<OnConflictAction>(OnConflictAction value);

template<>
const char* EnumUtil::ToChars<OnCreateConflict>(OnCreateConflict value);

template<>
const char* EnumUtil::ToChars<OnEntryNotFound>(OnEntryNotFound value);

template<>
const char* EnumUtil::ToChars<OperatorCachingMode>(OperatorCachingMode value);

template<>
const char* EnumUtil::ToChars<OperatorFinalResultType>(OperatorFinalResultType value);

template<>
const char* EnumUtil::ToChars<OperatorFinalizeResultType>(OperatorFinalizeResultType value);

template<>
const char* EnumUtil::ToChars<OperatorMatcherMode>(OperatorMatcherMode value);

template<>
const char* EnumUtil::ToChars<OperatorResultType>(OperatorResultType value);

template<>
const char* EnumUtil::ToChars<OptimizerHookPosition>(OptimizerHookPosition value);

template<>
const char* EnumUtil::ToChars<OptimizerType>(OptimizerType value);

template<>
const char* EnumUtil::ToChars<OrderByColumnType>(OrderByColumnType value);

template<>
const char* EnumUtil::ToChars<OrderByNullType>(OrderByNullType value);

template<>
const char* EnumUtil::ToChars<OrderByStatistics>(OrderByStatistics value);

template<>
const char* EnumUtil::ToChars<OrderPreservationType>(OrderPreservationType value);

template<>
const char* EnumUtil::ToChars<OrderType>(OrderType value);

template<>
const char* EnumUtil::ToChars<OrdinalityType>(OrdinalityType value);

template<>
const char* EnumUtil::ToChars<OutputStream>(OutputStream value);

template<>
const char* EnumUtil::ToChars<ParseInfoType>(ParseInfoType value);

template<>
const char* EnumUtil::ToChars<ParseResultType>(ParseResultType value);

template<>
const char* EnumUtil::ToChars<PartitionedColumnDataType>(PartitionedColumnDataType value);

template<>
const char* EnumUtil::ToChars<PartitionedTupleDataType>(PartitionedTupleDataType value);

template<>
const char* EnumUtil::ToChars<PatternMatchType>(PatternMatchType value);

template<>
const char* EnumUtil::ToChars<PatternMemo>(PatternMemo value);

template<>
const char* EnumUtil::ToChars<PatternOp>(PatternOp value);

template<>
const char* EnumUtil::ToChars<PhysicalOperatorType>(PhysicalOperatorType value);

template<>
const char* EnumUtil::ToChars<PhysicalTableScanExecutionStrategy>(PhysicalTableScanExecutionStrategy value);

template<>
const char* EnumUtil::ToChars<PhysicalType>(PhysicalType value);

template<>
const char* EnumUtil::ToChars<PipelineBroadcastExchangeConsumerMode>(PipelineBroadcastExchangeConsumerMode value);

template<>
const char* EnumUtil::ToChars<PipelineBroadcastExchangeOrderMode>(PipelineBroadcastExchangeOrderMode value);

template<>
const char* EnumUtil::ToChars<PipelineBroadcastExchangeScanMode>(PipelineBroadcastExchangeScanMode value);

template<>
const char* EnumUtil::ToChars<PipelineInputMode>(PipelineInputMode value);

template<>
const char* EnumUtil::ToChars<PipelineScheduleMode>(PipelineScheduleMode value);

template<>
const char* EnumUtil::ToChars<PipelineScheduleStageType>(PipelineScheduleStageType value);

template<>
const char* EnumUtil::ToChars<PragmaType>(PragmaType value);

template<>
const char* EnumUtil::ToChars<PreparedParamType>(PreparedParamType value);

template<>
const char* EnumUtil::ToChars<PreparedStatementMode>(PreparedStatementMode value);

template<>
const char* EnumUtil::ToChars<PreserveOrderType>(PreserveOrderType value);

template<>
const char* EnumUtil::ToChars<ProfilingCoverage>(ProfilingCoverage value);

template<>
const char* EnumUtil::ToChars<ProfilingParameterNames>(ProfilingParameterNames value);

template<>
const char* EnumUtil::ToChars<ProgressInvariant>(ProgressInvariant value);

template<>
const char* EnumUtil::ToChars<PushdownExtractSupport>(PushdownExtractSupport value);

template<>
const char* EnumUtil::ToChars<QualifiedNameToStringMode>(QualifiedNameToStringMode value);

template<>
const char* EnumUtil::ToChars<QuantileSerializationType>(QuantileSerializationType value);

template<>
const char* EnumUtil::ToChars<QueryNodeType>(QueryNodeType value);

template<>
const char* EnumUtil::ToChars<QueryResultMemoryType>(QueryResultMemoryType value);

template<>
const char* EnumUtil::ToChars<QueryResultState>(QueryResultState value);

template<>
const char* EnumUtil::ToChars<RecoveryMode>(RecoveryMode value);

template<>
const char* EnumUtil::ToChars<RecursiveCTEPipelineMetricType>(RecursiveCTEPipelineMetricType value);

template<>
const char* EnumUtil::ToChars<RecursiveCTESourcePhase>(RecursiveCTESourcePhase value);

template<>
const char* EnumUtil::ToChars<RecursiveProbeSidePreference>(RecursiveProbeSidePreference value);

template<>
const char* EnumUtil::ToChars<RegexMatchOperatorSemantics>(RegexMatchOperatorSemantics value);

template<>
const char* EnumUtil::ToChars<RelationType>(RelationType value);

template<>
const char* EnumUtil::ToChars<RemoteCapability>(RemoteCapability value);

template<>
const char* EnumUtil::ToChars<RemoveUnusedColumnsMode>(RemoveUnusedColumnsMode value);

template<>
const char* EnumUtil::ToChars<RenderMode>(RenderMode value);

template<>
const char* EnumUtil::ToChars<RequestSizing>(RequestSizing value);

template<>
const char* EnumUtil::ToChars<RequestType>(RequestType value);

template<>
const char* EnumUtil::ToChars<ResultEagerness>(ResultEagerness value);

template<>
const char* EnumUtil::ToChars<ResultLifetime>(ResultLifetime value);

template<>
const char* EnumUtil::ToChars<ResultModifierType>(ResultModifierType value);

template<>
const char* EnumUtil::ToChars<ResultOrdering>(ResultOrdering value);

template<>
const char* EnumUtil::ToChars<RoleOption>(RoleOption value);

template<>
const char* EnumUtil::ToChars<RowGroupAppendMode>(RowGroupAppendMode value);

template<>
const char* EnumUtil::ToChars<RowIdHandling>(RowIdHandling value);

template<>
const char* EnumUtil::ToChars<SampleMethod>(SampleMethod value);

template<>
const char* EnumUtil::ToChars<SampleType>(SampleType value);

template<>
const char* EnumUtil::ToChars<SamplingState>(SamplingState value);

template<>
const char* EnumUtil::ToChars<ScanReadAheadAcquire>(ScanReadAheadAcquire value);

template<>
const char* EnumUtil::ToChars<ScanType>(ScanType value);

template<>
const char* EnumUtil::ToChars<SecretDisplayType>(SecretDisplayType value);

template<>
const char* EnumUtil::ToChars<SecretPersistType>(SecretPersistType value);

template<>
const char* EnumUtil::ToChars<SecretSerializationType>(SecretSerializationType value);

template<>
const char* EnumUtil::ToChars<SegmentTreeVerifyMode>(SegmentTreeVerifyMode value);

template<>
const char* EnumUtil::ToChars<SelectivityOptionalFilterType>(SelectivityOptionalFilterType value);

template<>
const char* EnumUtil::ToChars<SequenceInfo>(SequenceInfo value);

template<>
const char* EnumUtil::ToChars<SerializationVersionDeprecated>(SerializationVersionDeprecated value);

template<>
const char* EnumUtil::ToChars<SetOperationType>(SetOperationType value);

template<>
const char* EnumUtil::ToChars<SetScope>(SetScope value);

template<>
const char* EnumUtil::ToChars<SetType>(SetType value);

template<>
const char* EnumUtil::ToChars<SettingScope>(SettingScope value);

template<>
const char* EnumUtil::ToChars<ShowBehaviorType>(ShowBehaviorType value);

template<>
const char* EnumUtil::ToChars<ShowType>(ShowType value);

template<>
const char* EnumUtil::ToChars<SimplifiedTokenType>(SimplifiedTokenType value);

template<>
const char* EnumUtil::ToChars<SinkCombineResultType>(SinkCombineResultType value);

template<>
const char* EnumUtil::ToChars<SinkFinalizeType>(SinkFinalizeType value);

template<>
const char* EnumUtil::ToChars<SinkNextBatchType>(SinkNextBatchType value);

template<>
const char* EnumUtil::ToChars<SinkResultType>(SinkResultType value);

template<>
const char* EnumUtil::ToChars<SortKeyType>(SortKeyType value);

template<>
const char* EnumUtil::ToChars<SourceBatchIndexState>(SourceBatchIndexState value);

template<>
const char* EnumUtil::ToChars<SourceResultType>(SourceResultType value);

template<>
const char* EnumUtil::ToChars<SqlCompatibility>(SqlCompatibility value);

template<>
const char* EnumUtil::ToChars<StarExpressionType>(StarExpressionType value);

template<>
const char* EnumUtil::ToChars<StateMemoryOwnership>(StateMemoryOwnership value);

template<>
const char* EnumUtil::ToChars<StatementReturnType>(StatementReturnType value);

template<>
const char* EnumUtil::ToChars<StatementType>(StatementType value);

template<>
const char* EnumUtil::ToChars<StatisticsPropagationMode>(StatisticsPropagationMode value);

template<>
const char* EnumUtil::ToChars<StatisticsType>(StatisticsType value);

template<>
const char* EnumUtil::ToChars<StatsInfo>(StatsInfo value);

template<>
const char* EnumUtil::ToChars<StorageBlockPrefetch>(StorageBlockPrefetch value);

template<>
const char* EnumUtil::ToChars<StorageIndexType>(StorageIndexType value);

template<>
const char* EnumUtil::ToChars<StrTimeSpecifier>(StrTimeSpecifier value);

template<>
const char* EnumUtil::ToChars<SubqueryType>(SubqueryType value);

template<>
const char* EnumUtil::ToChars<SuggestionState>(SuggestionState value);

template<>
const char* EnumUtil::ToChars<TableColumnType>(TableColumnType value);

template<>
const char* EnumUtil::ToChars<TableFilterPushdown>(TableFilterPushdown value);

template<>
const char* EnumUtil::ToChars<TableFilterType>(TableFilterType value);

template<>
const char* EnumUtil::ToChars<TableFunctionIdentifierConversion>(TableFunctionIdentifierConversion value);

template<>
const char* EnumUtil::ToChars<TableFunctionParallelism>(TableFunctionParallelism value);

template<>
const char* EnumUtil::ToChars<TablePartitionInfo>(TablePartitionInfo value);

template<>
const char* EnumUtil::ToChars<TableReferenceType>(TableReferenceType value);

template<>
const char* EnumUtil::ToChars<TaskExecutionMode>(TaskExecutionMode value);

template<>
const char* EnumUtil::ToChars<TaskExecutionResult>(TaskExecutionResult value);

template<>
const char* EnumUtil::ToChars<TaskSchedulerType>(TaskSchedulerType value);

template<>
const char* EnumUtil::ToChars<TemporaryBufferSize>(TemporaryBufferSize value);

template<>
const char* EnumUtil::ToChars<TemporaryCompressionLevel>(TemporaryCompressionLevel value);

template<>
const char* EnumUtil::ToChars<ThreadPinMode>(ThreadPinMode value);

template<>
const char* EnumUtil::ToChars<TimestampCastResult>(TimestampCastResult value);

template<>
const char* EnumUtil::ToChars<TokenType>(TokenType value);

template<>
const char* EnumUtil::ToChars<TransactionInvalidationPolicy>(TransactionInvalidationPolicy value);

template<>
const char* EnumUtil::ToChars<TransactionIsolationLevel>(TransactionIsolationLevel value);

template<>
const char* EnumUtil::ToChars<TransactionModifierType>(TransactionModifierType value);

template<>
const char* EnumUtil::ToChars<TransactionType>(TransactionType value);

template<>
const char* EnumUtil::ToChars<TriggerEventType>(TriggerEventType value);

template<>
const char* EnumUtil::ToChars<TriggerForEach>(TriggerForEach value);

template<>
const char* EnumUtil::ToChars<TriggerTiming>(TriggerTiming value);

template<>
const char* EnumUtil::ToChars<TupleDataNestednessType>(TupleDataNestednessType value);

template<>
const char* EnumUtil::ToChars<TupleDataPinProperties>(TupleDataPinProperties value);

template<>
const char* EnumUtil::ToChars<TupleDataValidityType>(TupleDataValidityType value);

template<>
const char* EnumUtil::ToChars<UndoFlags>(UndoFlags value);

template<>
const char* EnumUtil::ToChars<UnionInvalidReason>(UnionInvalidReason value);

template<>
const char* EnumUtil::ToChars<VacuumIndexStrategy>(VacuumIndexStrategy value);

template<>
const char* EnumUtil::ToChars<VariantChildLookupMode>(VariantChildLookupMode value);

template<>
const char* EnumUtil::ToChars<VariantComparisonType>(VariantComparisonType value);

template<>
const char* EnumUtil::ToChars<VariantLogicalType>(VariantLogicalType value);

template<>
const char* EnumUtil::ToChars<VariantStatsShreddingState>(VariantStatsShreddingState value);

template<>
const char* EnumUtil::ToChars<VectorBufferType>(VectorBufferType value);

template<>
const char* EnumUtil::ToChars<VectorPrepareState>(VectorPrepareState value);

template<>
const char* EnumUtil::ToChars<VectorType>(VectorType value);

template<>
const char* EnumUtil::ToChars<VerifyExistenceType>(VerifyExistenceType value);

template<>
const char* EnumUtil::ToChars<VersionCompressionResult>(VersionCompressionResult value);

template<>
const char* EnumUtil::ToChars<VertexType>(VertexType value);

template<>
const char* EnumUtil::ToChars<ViewSecurityType>(ViewSecurityType value);

template<>
const char* EnumUtil::ToChars<WALType>(WALType value);

template<>
const char* EnumUtil::ToChars<WindowAggregationMode>(WindowAggregationMode value);

template<>
const char* EnumUtil::ToChars<WindowBoundary>(WindowBoundary value);

template<>
const char* EnumUtil::ToChars<WindowExcludeMode>(WindowExcludeMode value);

template<>
const char* EnumUtil::ToChars<WindowMergeSortStage>(WindowMergeSortStage value);


template<>
ARTConflictType EnumUtil::FromString<ARTConflictType>(std::string_view value);

template<>
ARTScanNodeResult EnumUtil::FromString<ARTScanNodeResult>(std::string_view value);

template<>
ARTScanProgress EnumUtil::FromString<ARTScanProgress>(std::string_view value);

template<>
ARTSearchResult EnumUtil::FromString<ARTSearchResult>(std::string_view value);

template<>
AccessMode EnumUtil::FromString<AccessMode>(std::string_view value);

template<>
AclMode EnumUtil::FromString<AclMode>(std::string_view value);

template<>
AdaptiveFilterSource EnumUtil::FromString<AdaptiveFilterSource>(std::string_view value);

template<>
AggregateCombineType EnumUtil::FromString<AggregateCombineType>(std::string_view value);

template<>
AggregateDistinctDependent EnumUtil::FromString<AggregateDistinctDependent>(std::string_view value);

template<>
AggregateHandling EnumUtil::FromString<AggregateHandling>(std::string_view value);

template<>
AggregateOrderDependent EnumUtil::FromString<AggregateOrderDependent>(std::string_view value);

template<>
AggregateRewritePolicy EnumUtil::FromString<AggregateRewritePolicy>(std::string_view value);

template<>
AggregateRewriteSourceType EnumUtil::FromString<AggregateRewriteSourceType>(std::string_view value);

template<>
AggregateStateExportMode EnumUtil::FromString<AggregateStateExportMode>(std::string_view value);

template<>
AggregateType EnumUtil::FromString<AggregateType>(std::string_view value);

template<>
AlterDatabaseType EnumUtil::FromString<AlterDatabaseType>(std::string_view value);

template<>
AlterForeignKeyType EnumUtil::FromString<AlterForeignKeyType>(std::string_view value);

template<>
AlterIndexType EnumUtil::FromString<AlterIndexType>(std::string_view value);

template<>
AlterScalarFunctionType EnumUtil::FromString<AlterScalarFunctionType>(std::string_view value);

template<>
AlterSchemaType EnumUtil::FromString<AlterSchemaType>(std::string_view value);

template<>
AlterSequenceType EnumUtil::FromString<AlterSequenceType>(std::string_view value);

template<>
AlterTableFunctionType EnumUtil::FromString<AlterTableFunctionType>(std::string_view value);

template<>
AlterTableType EnumUtil::FromString<AlterTableType>(std::string_view value);

template<>
AlterType EnumUtil::FromString<AlterType>(std::string_view value);

template<>
AlterViewType EnumUtil::FromString<AlterViewType>(std::string_view value);

template<>
AppenderType EnumUtil::FromString<AppenderType>(std::string_view value);

template<>
ArrowArrayPhysicalType EnumUtil::FromString<ArrowArrayPhysicalType>(std::string_view value);

template<>
ArrowDateTimeType EnumUtil::FromString<ArrowDateTimeType>(std::string_view value);

template<>
ArrowFormatVersion EnumUtil::FromString<ArrowFormatVersion>(std::string_view value);

template<>
ArrowOffsetSize EnumUtil::FromString<ArrowOffsetSize>(std::string_view value);

template<>
ArrowTypeInfoType EnumUtil::FromString<ArrowTypeInfoType>(std::string_view value);

template<>
ArrowVariableSizeType EnumUtil::FromString<ArrowVariableSizeType>(std::string_view value);

template<>
AsyncResultType EnumUtil::FromString<AsyncResultType>(std::string_view value);

template<>
AsyncResultsExecutionMode EnumUtil::FromString<AsyncResultsExecutionMode>(std::string_view value);

template<>
BaseColumnPrunerMode EnumUtil::FromString<BaseColumnPrunerMode>(std::string_view value);

template<>
BinderType EnumUtil::FromString<BinderType>(std::string_view value);

template<>
BindingMode EnumUtil::FromString<BindingMode>(std::string_view value);

template<>
BitpackingMode EnumUtil::FromString<BitpackingMode>(std::string_view value);

template<>
BlockIteratorStateType EnumUtil::FromString<BlockIteratorStateType>(std::string_view value);

template<>
BlockState EnumUtil::FromString<BlockState>(std::string_view value);

template<>
BufferedIndexReplay EnumUtil::FromString<BufferedIndexReplay>(std::string_view value);

template<>
CAPIResultSetType EnumUtil::FromString<CAPIResultSetType>(std::string_view value);

template<>
CSVState EnumUtil::FromString<CSVState>(std::string_view value);

template<>
CTEExecutionMode EnumUtil::FromString<CTEExecutionMode>(std::string_view value);

template<>
CTEMaterialize EnumUtil::FromString<CTEMaterialize>(std::string_view value);

template<>
CacheBlockState EnumUtil::FromString<CacheBlockState>(std::string_view value);

template<>
CacheValidationMode EnumUtil::FromString<CacheValidationMode>(std::string_view value);

template<>
CachingMode EnumUtil::FromString<CachingMode>(std::string_view value);

template<>
CanUnloadResult EnumUtil::FromString<CanUnloadResult>(std::string_view value);

template<>
CatalogLookupBehavior EnumUtil::FromString<CatalogLookupBehavior>(std::string_view value);

template<>
CatalogType EnumUtil::FromString<CatalogType>(std::string_view value);

template<>
CheckpointAbort EnumUtil::FromString<CheckpointAbort>(std::string_view value);

template<>
CheckpointOnDetach EnumUtil::FromString<CheckpointOnDetach>(std::string_view value);

template<>
ChunkInfoType EnumUtil::FromString<ChunkInfoType>(std::string_view value);

template<>
ClientInterruptState EnumUtil::FromString<ClientInterruptState>(std::string_view value);

template<>
ColumnDataAllocatorType EnumUtil::FromString<ColumnDataAllocatorType>(std::string_view value);

template<>
ColumnDataScanProperties EnumUtil::FromString<ColumnDataScanProperties>(std::string_view value);

template<>
ColumnIndexType EnumUtil::FromString<ColumnIndexType>(std::string_view value);

template<>
ColumnSegmentType EnumUtil::FromString<ColumnSegmentType>(std::string_view value);

template<>
CompressedMaterializationDirection EnumUtil::FromString<CompressedMaterializationDirection>(std::string_view value);

template<>
CompressedMaterializationType EnumUtil::FromString<CompressedMaterializationType>(std::string_view value);

template<>
CompressionType EnumUtil::FromString<CompressionType>(std::string_view value);

template<>
CompressionValidity EnumUtil::FromString<CompressionValidity>(std::string_view value);

template<>
ConflictManagerMode EnumUtil::FromString<ConflictManagerMode>(std::string_view value);

template<>
ConstraintCheckMode EnumUtil::FromString<ConstraintCheckMode>(std::string_view value);

template<>
ConstraintType EnumUtil::FromString<ConstraintType>(std::string_view value);

template<>
CoordinateReferenceSystemType EnumUtil::FromString<CoordinateReferenceSystemType>(std::string_view value);

template<>
CopyFunctionFlushBatchReason EnumUtil::FromString<CopyFunctionFlushBatchReason>(std::string_view value);

template<>
CopyFunctionReturnType EnumUtil::FromString<CopyFunctionReturnType>(std::string_view value);

template<>
CopyOverwriteMode EnumUtil::FromString<CopyOverwriteMode>(std::string_view value);

template<>
CopyToType EnumUtil::FromString<CopyToType>(std::string_view value);

template<>
CryptoHashFunction EnumUtil::FromString<CryptoHashFunction>(std::string_view value);

template<>
DataFileType EnumUtil::FromString<DataFileType>(std::string_view value);

template<>
DateCastResult EnumUtil::FromString<DateCastResult>(std::string_view value);

template<>
DatePartSpecifier EnumUtil::FromString<DatePartSpecifier>(std::string_view value);

template<>
DebugInitialize EnumUtil::FromString<DebugInitialize>(std::string_view value);

template<>
DebugOrderVerification EnumUtil::FromString<DebugOrderVerification>(std::string_view value);

template<>
DebugProgressVerification EnumUtil::FromString<DebugProgressVerification>(std::string_view value);

template<>
DebugStatementVerification EnumUtil::FromString<DebugStatementVerification>(std::string_view value);

template<>
DebugVectorVerification EnumUtil::FromString<DebugVectorVerification>(std::string_view value);

template<>
DebugVerificationMode EnumUtil::FromString<DebugVerificationMode>(std::string_view value);

template<>
DecimalBitWidth EnumUtil::FromString<DecimalBitWidth>(std::string_view value);

template<>
DefaultOrderByNullType EnumUtil::FromString<DefaultOrderByNullType>(std::string_view value);

template<>
DeferredRuntimeFilterType EnumUtil::FromString<DeferredRuntimeFilterType>(std::string_view value);

template<>
DeleteIdState EnumUtil::FromString<DeleteIdState>(std::string_view value);

template<>
DependencyEntryType EnumUtil::FromString<DependencyEntryType>(std::string_view value);

template<>
DeprecatedIndexType EnumUtil::FromString<DeprecatedIndexType>(std::string_view value);

template<>
DestroyBufferUpon EnumUtil::FromString<DestroyBufferUpon>(std::string_view value);

template<>
DialectCompatibilityMode EnumUtil::FromString<DialectCompatibilityMode>(std::string_view value);

template<>
DictFSSTMode EnumUtil::FromString<DictFSSTMode>(std::string_view value);

template<>
DistinctCountSource EnumUtil::FromString<DistinctCountSource>(std::string_view value);

template<>
DistinctType EnumUtil::FromString<DistinctType>(std::string_view value);

template<>
ErrorType EnumUtil::FromString<ErrorType>(std::string_view value);

template<>
ExceptionFormatValueType EnumUtil::FromString<ExceptionFormatValueType>(std::string_view value);

template<>
ExceptionType EnumUtil::FromString<ExceptionType>(std::string_view value);

template<>
ExplainFormatShape EnumUtil::FromString<ExplainFormatShape>(std::string_view value);

template<>
ExplainOutputType EnumUtil::FromString<ExplainOutputType>(std::string_view value);

template<>
ExplainType EnumUtil::FromString<ExplainType>(std::string_view value);

template<>
ExponentType EnumUtil::FromString<ExponentType>(std::string_view value);

template<>
ExpressionClass EnumUtil::FromString<ExpressionClass>(std::string_view value);

template<>
ExpressionTailType EnumUtil::FromString<ExpressionTailType>(std::string_view value);

template<>
ExpressionType EnumUtil::FromString<ExpressionType>(std::string_view value);

template<>
ExtensionABIType EnumUtil::FromString<ExtensionABIType>(std::string_view value);

template<>
ExtensionInstallMode EnumUtil::FromString<ExtensionInstallMode>(std::string_view value);

template<>
ExtensionLoadResult EnumUtil::FromString<ExtensionLoadResult>(std::string_view value);

template<>
ExtensionRepositoryAccess EnumUtil::FromString<ExtensionRepositoryAccess>(std::string_view value);

template<>
ExtensionRepositoryType EnumUtil::FromString<ExtensionRepositoryType>(std::string_view value);

template<>
ExtensionUpdateResultTag EnumUtil::FromString<ExtensionUpdateResultTag>(std::string_view value);

template<>
ExternalResourceOperation EnumUtil::FromString<ExternalResourceOperation>(std::string_view value);

template<>
ExtraDropInfoType EnumUtil::FromString<ExtraDropInfoType>(std::string_view value);

template<>
ExtraPersistentColumnDataType EnumUtil::FromString<ExtraPersistentColumnDataType>(std::string_view value);

template<>
FileBufferType EnumUtil::FromString<FileBufferType>(std::string_view value);

template<>
FileExpandResult EnumUtil::FromString<FileExpandResult>(std::string_view value);

template<>
FileGlobOptions EnumUtil::FromString<FileGlobOptions>(std::string_view value);

template<>
FileIOMode EnumUtil::FromString<FileIOMode>(std::string_view value);

template<>
FileLockType EnumUtil::FromString<FileLockType>(std::string_view value);

template<>
FileNameSegmentType EnumUtil::FromString<FileNameSegmentType>(std::string_view value);

template<>
FileSyncMode EnumUtil::FromString<FileSyncMode>(std::string_view value);

template<>
FileSyncParallelism EnumUtil::FromString<FileSyncParallelism>(std::string_view value);

template<>
FileWriteMode EnumUtil::FromString<FileWriteMode>(std::string_view value);

template<>
FilterPropagateResult EnumUtil::FromString<FilterPropagateResult>(std::string_view value);

template<>
FilterReorder EnumUtil::FromString<FilterReorder>(std::string_view value);

template<>
ForeignKeyType EnumUtil::FromString<ForeignKeyType>(std::string_view value);

template<>
FormatArgumentType EnumUtil::FromString<FormatArgumentType>(std::string_view value);

template<>
FunctionCollationHandling EnumUtil::FromString<FunctionCollationHandling>(std::string_view value);

template<>
FunctionErrors EnumUtil::FromString<FunctionErrors>(std::string_view value);

template<>
FunctionNullHandling EnumUtil::FromString<FunctionNullHandling>(std::string_view value);

template<>
FunctionParameterKind EnumUtil::FromString<FunctionParameterKind>(std::string_view value);

template<>
FunctionStability EnumUtil::FromString<FunctionStability>(std::string_view value);

template<>
GateStatus EnumUtil::FromString<GateStatus>(std::string_view value);

template<>
GeometryStorageType EnumUtil::FromString<GeometryStorageType>(std::string_view value);

template<>
GeometryType EnumUtil::FromString<GeometryType>(std::string_view value);

template<>
GroupByExpressionInfoType EnumUtil::FromString<GroupByExpressionInfoType>(std::string_view value);

template<>
HLLStorageType EnumUtil::FromString<HLLStorageType>(std::string_view value);

template<>
HTTPClientCachePolicy EnumUtil::FromString<HTTPClientCachePolicy>(std::string_view value);

template<>
HTTPStatusCode EnumUtil::FromString<HTTPStatusCode>(std::string_view value);

template<>
HTTPTransportReusePolicy EnumUtil::FromString<HTTPTransportReusePolicy>(std::string_view value);

template<>
IdentifierCaseMode EnumUtil::FromString<IdentifierCaseMode>(std::string_view value);

template<>
IndexAppendMode EnumUtil::FromString<IndexAppendMode>(std::string_view value);

template<>
IndexBindState EnumUtil::FromString<IndexBindState>(std::string_view value);

template<>
IndexConstraintType EnumUtil::FromString<IndexConstraintType>(std::string_view value);

template<>
IndexDeltaType EnumUtil::FromString<IndexDeltaType>(std::string_view value);

template<>
InsertColumnOrder EnumUtil::FromString<InsertColumnOrder>(std::string_view value);

template<>
InterruptMode EnumUtil::FromString<InterruptMode>(std::string_view value);

template<>
JoinFilterPushdownMode EnumUtil::FromString<JoinFilterPushdownMode>(std::string_view value);

template<>
JoinOrderOperatorType EnumUtil::FromString<JoinOrderOperatorType>(std::string_view value);

template<>
JoinRefType EnumUtil::FromString<JoinRefType>(std::string_view value);

template<>
JoinType EnumUtil::FromString<JoinType>(std::string_view value);

template<>
KeywordCase EnumUtil::FromString<KeywordCase>(std::string_view value);

template<>
KeywordCategory EnumUtil::FromString<KeywordCategory>(std::string_view value);

template<>
LambdaSyntax EnumUtil::FromString<LambdaSyntax>(std::string_view value);

template<>
LambdaSyntaxType EnumUtil::FromString<LambdaSyntaxType>(std::string_view value);

template<>
LimitNodeType EnumUtil::FromString<LimitNodeType>(std::string_view value);

template<>
LimitValueType EnumUtil::FromString<LimitValueType>(std::string_view value);

template<>
LiteralKind EnumUtil::FromString<LiteralKind>(std::string_view value);

template<>
LoadType EnumUtil::FromString<LoadType>(std::string_view value);

template<>
LogContextScope EnumUtil::FromString<LogContextScope>(std::string_view value);

template<>
LogLevel EnumUtil::FromString<LogLevel>(std::string_view value);

template<>
LogMode EnumUtil::FromString<LogMode>(std::string_view value);

template<>
LoggingTargetTable EnumUtil::FromString<LoggingTargetTable>(std::string_view value);

template<>
LogicalOperatorRepeatability EnumUtil::FromString<LogicalOperatorRepeatability>(std::string_view value);

template<>
LogicalOperatorType EnumUtil::FromString<LogicalOperatorType>(std::string_view value);

template<>
LogicalPlanVerificationIssueCode EnumUtil::FromString<LogicalPlanVerificationIssueCode>(std::string_view value);

template<>
LogicalPlanVerificationPathComponentType EnumUtil::FromString<LogicalPlanVerificationPathComponentType>(std::string_view value);

template<>
LogicalPlanVerificationPhase EnumUtil::FromString<LogicalPlanVerificationPhase>(std::string_view value);

template<>
LogicalTypeId EnumUtil::FromString<LogicalTypeId>(std::string_view value);

template<>
LogicalTypeInfoType EnumUtil::FromString<LogicalTypeInfoType>(std::string_view value);

template<>
LookupResultType EnumUtil::FromString<LookupResultType>(std::string_view value);

template<>
MacroType EnumUtil::FromString<MacroType>(std::string_view value);

template<>
MapInvalidReason EnumUtil::FromString<MapInvalidReason>(std::string_view value);

template<>
MatchMode EnumUtil::FromString<MatchMode>(std::string_view value);

template<>
MatchRecognizeAfterMatch EnumUtil::FromString<MatchRecognizeAfterMatch>(std::string_view value);

template<>
MatchRecognizeClauseKind EnumUtil::FromString<MatchRecognizeClauseKind>(std::string_view value);

template<>
MatchRecognizePatternType EnumUtil::FromString<MatchRecognizePatternType>(std::string_view value);

template<>
MatchRecognizeRows EnumUtil::FromString<MatchRecognizeRows>(std::string_view value);

template<>
MemoryTag EnumUtil::FromString<MemoryTag>(std::string_view value);

template<>
MergeActionCondition EnumUtil::FromString<MergeActionCondition>(std::string_view value);

template<>
MergeActionType EnumUtil::FromString<MergeActionType>(std::string_view value);

template<>
MetaPipelineType EnumUtil::FromString<MetaPipelineType>(std::string_view value);

template<>
Monotonicity EnumUtil::FromString<Monotonicity>(std::string_view value);

template<>
MultiFileClaimResult EnumUtil::FromString<MultiFileClaimResult>(std::string_view value);

template<>
MultiFileColumnMappingMode EnumUtil::FromString<MultiFileColumnMappingMode>(std::string_view value);

template<>
MultiFileDecodeResult EnumUtil::FromString<MultiFileDecodeResult>(std::string_view value);

template<>
MultiFileFileState EnumUtil::FromString<MultiFileFileState>(std::string_view value);

template<>
MultiFileJobState EnumUtil::FromString<MultiFileJobState>(std::string_view value);

template<>
NType EnumUtil::FromString<NType>(std::string_view value);

template<>
NewLineIdentifier EnumUtil::FromString<NewLineIdentifier>(std::string_view value);

template<>
OnConflictAction EnumUtil::FromString<OnConflictAction>(std::string_view value);

template<>
OnCreateConflict EnumUtil::FromString<OnCreateConflict>(std::string_view value);

template<>
OnEntryNotFound EnumUtil::FromString<OnEntryNotFound>(std::string_view value);

template<>
OperatorCachingMode EnumUtil::FromString<OperatorCachingMode>(std::string_view value);

template<>
OperatorFinalResultType EnumUtil::FromString<OperatorFinalResultType>(std::string_view value);

template<>
OperatorFinalizeResultType EnumUtil::FromString<OperatorFinalizeResultType>(std::string_view value);

template<>
OperatorMatcherMode EnumUtil::FromString<OperatorMatcherMode>(std::string_view value);

template<>
OperatorResultType EnumUtil::FromString<OperatorResultType>(std::string_view value);

template<>
OptimizerHookPosition EnumUtil::FromString<OptimizerHookPosition>(std::string_view value);

template<>
OptimizerType EnumUtil::FromString<OptimizerType>(std::string_view value);

template<>
OrderByColumnType EnumUtil::FromString<OrderByColumnType>(std::string_view value);

template<>
OrderByNullType EnumUtil::FromString<OrderByNullType>(std::string_view value);

template<>
OrderByStatistics EnumUtil::FromString<OrderByStatistics>(std::string_view value);

template<>
OrderPreservationType EnumUtil::FromString<OrderPreservationType>(std::string_view value);

template<>
OrderType EnumUtil::FromString<OrderType>(std::string_view value);

template<>
OrdinalityType EnumUtil::FromString<OrdinalityType>(std::string_view value);

template<>
OutputStream EnumUtil::FromString<OutputStream>(std::string_view value);

template<>
ParseInfoType EnumUtil::FromString<ParseInfoType>(std::string_view value);

template<>
ParseResultType EnumUtil::FromString<ParseResultType>(std::string_view value);

template<>
PartitionedColumnDataType EnumUtil::FromString<PartitionedColumnDataType>(std::string_view value);

template<>
PartitionedTupleDataType EnumUtil::FromString<PartitionedTupleDataType>(std::string_view value);

template<>
PatternMatchType EnumUtil::FromString<PatternMatchType>(std::string_view value);

template<>
PatternMemo EnumUtil::FromString<PatternMemo>(std::string_view value);

template<>
PatternOp EnumUtil::FromString<PatternOp>(std::string_view value);

template<>
PhysicalOperatorType EnumUtil::FromString<PhysicalOperatorType>(std::string_view value);

template<>
PhysicalTableScanExecutionStrategy EnumUtil::FromString<PhysicalTableScanExecutionStrategy>(std::string_view value);

template<>
PhysicalType EnumUtil::FromString<PhysicalType>(std::string_view value);

template<>
PipelineBroadcastExchangeConsumerMode EnumUtil::FromString<PipelineBroadcastExchangeConsumerMode>(std::string_view value);

template<>
PipelineBroadcastExchangeOrderMode EnumUtil::FromString<PipelineBroadcastExchangeOrderMode>(std::string_view value);

template<>
PipelineBroadcastExchangeScanMode EnumUtil::FromString<PipelineBroadcastExchangeScanMode>(std::string_view value);

template<>
PipelineInputMode EnumUtil::FromString<PipelineInputMode>(std::string_view value);

template<>
PipelineScheduleMode EnumUtil::FromString<PipelineScheduleMode>(std::string_view value);

template<>
PipelineScheduleStageType EnumUtil::FromString<PipelineScheduleStageType>(std::string_view value);

template<>
PragmaType EnumUtil::FromString<PragmaType>(std::string_view value);

template<>
PreparedParamType EnumUtil::FromString<PreparedParamType>(std::string_view value);

template<>
PreparedStatementMode EnumUtil::FromString<PreparedStatementMode>(std::string_view value);

template<>
PreserveOrderType EnumUtil::FromString<PreserveOrderType>(std::string_view value);

template<>
ProfilingCoverage EnumUtil::FromString<ProfilingCoverage>(std::string_view value);

template<>
ProfilingParameterNames EnumUtil::FromString<ProfilingParameterNames>(std::string_view value);

template<>
ProgressInvariant EnumUtil::FromString<ProgressInvariant>(std::string_view value);

template<>
PushdownExtractSupport EnumUtil::FromString<PushdownExtractSupport>(std::string_view value);

template<>
QualifiedNameToStringMode EnumUtil::FromString<QualifiedNameToStringMode>(std::string_view value);

template<>
QuantileSerializationType EnumUtil::FromString<QuantileSerializationType>(std::string_view value);

template<>
QueryNodeType EnumUtil::FromString<QueryNodeType>(std::string_view value);

template<>
QueryResultMemoryType EnumUtil::FromString<QueryResultMemoryType>(std::string_view value);

template<>
QueryResultState EnumUtil::FromString<QueryResultState>(std::string_view value);

template<>
RecoveryMode EnumUtil::FromString<RecoveryMode>(std::string_view value);

template<>
RecursiveCTEPipelineMetricType EnumUtil::FromString<RecursiveCTEPipelineMetricType>(std::string_view value);

template<>
RecursiveCTESourcePhase EnumUtil::FromString<RecursiveCTESourcePhase>(std::string_view value);

template<>
RecursiveProbeSidePreference EnumUtil::FromString<RecursiveProbeSidePreference>(std::string_view value);

template<>
RegexMatchOperatorSemantics EnumUtil::FromString<RegexMatchOperatorSemantics>(std::string_view value);

template<>
RelationType EnumUtil::FromString<RelationType>(std::string_view value);

template<>
RemoteCapability EnumUtil::FromString<RemoteCapability>(std::string_view value);

template<>
RemoveUnusedColumnsMode EnumUtil::FromString<RemoveUnusedColumnsMode>(std::string_view value);

template<>
RenderMode EnumUtil::FromString<RenderMode>(std::string_view value);

template<>
RequestSizing EnumUtil::FromString<RequestSizing>(std::string_view value);

template<>
RequestType EnumUtil::FromString<RequestType>(std::string_view value);

template<>
ResultEagerness EnumUtil::FromString<ResultEagerness>(std::string_view value);

template<>
ResultLifetime EnumUtil::FromString<ResultLifetime>(std::string_view value);

template<>
ResultModifierType EnumUtil::FromString<ResultModifierType>(std::string_view value);

template<>
ResultOrdering EnumUtil::FromString<ResultOrdering>(std::string_view value);

template<>
RoleOption EnumUtil::FromString<RoleOption>(std::string_view value);

template<>
RowGroupAppendMode EnumUtil::FromString<RowGroupAppendMode>(std::string_view value);

template<>
RowIdHandling EnumUtil::FromString<RowIdHandling>(std::string_view value);

template<>
SampleMethod EnumUtil::FromString<SampleMethod>(std::string_view value);

template<>
SampleType EnumUtil::FromString<SampleType>(std::string_view value);

template<>
SamplingState EnumUtil::FromString<SamplingState>(std::string_view value);

template<>
ScanReadAheadAcquire EnumUtil::FromString<ScanReadAheadAcquire>(std::string_view value);

template<>
ScanType EnumUtil::FromString<ScanType>(std::string_view value);

template<>
SecretDisplayType EnumUtil::FromString<SecretDisplayType>(std::string_view value);

template<>
SecretPersistType EnumUtil::FromString<SecretPersistType>(std::string_view value);

template<>
SecretSerializationType EnumUtil::FromString<SecretSerializationType>(std::string_view value);

template<>
SegmentTreeVerifyMode EnumUtil::FromString<SegmentTreeVerifyMode>(std::string_view value);

template<>
SelectivityOptionalFilterType EnumUtil::FromString<SelectivityOptionalFilterType>(std::string_view value);

template<>
SequenceInfo EnumUtil::FromString<SequenceInfo>(std::string_view value);

template<>
SerializationVersionDeprecated EnumUtil::FromString<SerializationVersionDeprecated>(std::string_view value);

template<>
SetOperationType EnumUtil::FromString<SetOperationType>(std::string_view value);

template<>
SetScope EnumUtil::FromString<SetScope>(std::string_view value);

template<>
SetType EnumUtil::FromString<SetType>(std::string_view value);

template<>
SettingScope EnumUtil::FromString<SettingScope>(std::string_view value);

template<>
ShowBehaviorType EnumUtil::FromString<ShowBehaviorType>(std::string_view value);

template<>
ShowType EnumUtil::FromString<ShowType>(std::string_view value);

template<>
SimplifiedTokenType EnumUtil::FromString<SimplifiedTokenType>(std::string_view value);

template<>
SinkCombineResultType EnumUtil::FromString<SinkCombineResultType>(std::string_view value);

template<>
SinkFinalizeType EnumUtil::FromString<SinkFinalizeType>(std::string_view value);

template<>
SinkNextBatchType EnumUtil::FromString<SinkNextBatchType>(std::string_view value);

template<>
SinkResultType EnumUtil::FromString<SinkResultType>(std::string_view value);

template<>
SortKeyType EnumUtil::FromString<SortKeyType>(std::string_view value);

template<>
SourceBatchIndexState EnumUtil::FromString<SourceBatchIndexState>(std::string_view value);

template<>
SourceResultType EnumUtil::FromString<SourceResultType>(std::string_view value);

template<>
SqlCompatibility EnumUtil::FromString<SqlCompatibility>(std::string_view value);

template<>
StarExpressionType EnumUtil::FromString<StarExpressionType>(std::string_view value);

template<>
StateMemoryOwnership EnumUtil::FromString<StateMemoryOwnership>(std::string_view value);

template<>
StatementReturnType EnumUtil::FromString<StatementReturnType>(std::string_view value);

template<>
StatementType EnumUtil::FromString<StatementType>(std::string_view value);

template<>
StatisticsPropagationMode EnumUtil::FromString<StatisticsPropagationMode>(std::string_view value);

template<>
StatisticsType EnumUtil::FromString<StatisticsType>(std::string_view value);

template<>
StatsInfo EnumUtil::FromString<StatsInfo>(std::string_view value);

template<>
StorageBlockPrefetch EnumUtil::FromString<StorageBlockPrefetch>(std::string_view value);

template<>
StorageIndexType EnumUtil::FromString<StorageIndexType>(std::string_view value);

template<>
StrTimeSpecifier EnumUtil::FromString<StrTimeSpecifier>(std::string_view value);

template<>
SubqueryType EnumUtil::FromString<SubqueryType>(std::string_view value);

template<>
SuggestionState EnumUtil::FromString<SuggestionState>(std::string_view value);

template<>
TableColumnType EnumUtil::FromString<TableColumnType>(std::string_view value);

template<>
TableFilterPushdown EnumUtil::FromString<TableFilterPushdown>(std::string_view value);

template<>
TableFilterType EnumUtil::FromString<TableFilterType>(std::string_view value);

template<>
TableFunctionIdentifierConversion EnumUtil::FromString<TableFunctionIdentifierConversion>(std::string_view value);

template<>
TableFunctionParallelism EnumUtil::FromString<TableFunctionParallelism>(std::string_view value);

template<>
TablePartitionInfo EnumUtil::FromString<TablePartitionInfo>(std::string_view value);

template<>
TableReferenceType EnumUtil::FromString<TableReferenceType>(std::string_view value);

template<>
TaskExecutionMode EnumUtil::FromString<TaskExecutionMode>(std::string_view value);

template<>
TaskExecutionResult EnumUtil::FromString<TaskExecutionResult>(std::string_view value);

template<>
TaskSchedulerType EnumUtil::FromString<TaskSchedulerType>(std::string_view value);

template<>
TemporaryBufferSize EnumUtil::FromString<TemporaryBufferSize>(std::string_view value);

template<>
TemporaryCompressionLevel EnumUtil::FromString<TemporaryCompressionLevel>(std::string_view value);

template<>
ThreadPinMode EnumUtil::FromString<ThreadPinMode>(std::string_view value);

template<>
TimestampCastResult EnumUtil::FromString<TimestampCastResult>(std::string_view value);

template<>
TokenType EnumUtil::FromString<TokenType>(std::string_view value);

template<>
TransactionInvalidationPolicy EnumUtil::FromString<TransactionInvalidationPolicy>(std::string_view value);

template<>
TransactionIsolationLevel EnumUtil::FromString<TransactionIsolationLevel>(std::string_view value);

template<>
TransactionModifierType EnumUtil::FromString<TransactionModifierType>(std::string_view value);

template<>
TransactionType EnumUtil::FromString<TransactionType>(std::string_view value);

template<>
TriggerEventType EnumUtil::FromString<TriggerEventType>(std::string_view value);

template<>
TriggerForEach EnumUtil::FromString<TriggerForEach>(std::string_view value);

template<>
TriggerTiming EnumUtil::FromString<TriggerTiming>(std::string_view value);

template<>
TupleDataNestednessType EnumUtil::FromString<TupleDataNestednessType>(std::string_view value);

template<>
TupleDataPinProperties EnumUtil::FromString<TupleDataPinProperties>(std::string_view value);

template<>
TupleDataValidityType EnumUtil::FromString<TupleDataValidityType>(std::string_view value);

template<>
UndoFlags EnumUtil::FromString<UndoFlags>(std::string_view value);

template<>
UnionInvalidReason EnumUtil::FromString<UnionInvalidReason>(std::string_view value);

template<>
VacuumIndexStrategy EnumUtil::FromString<VacuumIndexStrategy>(std::string_view value);

template<>
VariantChildLookupMode EnumUtil::FromString<VariantChildLookupMode>(std::string_view value);

template<>
VariantComparisonType EnumUtil::FromString<VariantComparisonType>(std::string_view value);

template<>
VariantLogicalType EnumUtil::FromString<VariantLogicalType>(std::string_view value);

template<>
VariantStatsShreddingState EnumUtil::FromString<VariantStatsShreddingState>(std::string_view value);

template<>
VectorBufferType EnumUtil::FromString<VectorBufferType>(std::string_view value);

template<>
VectorPrepareState EnumUtil::FromString<VectorPrepareState>(std::string_view value);

template<>
VectorType EnumUtil::FromString<VectorType>(std::string_view value);

template<>
VerifyExistenceType EnumUtil::FromString<VerifyExistenceType>(std::string_view value);

template<>
VersionCompressionResult EnumUtil::FromString<VersionCompressionResult>(std::string_view value);

template<>
VertexType EnumUtil::FromString<VertexType>(std::string_view value);

template<>
ViewSecurityType EnumUtil::FromString<ViewSecurityType>(std::string_view value);

template<>
WALType EnumUtil::FromString<WALType>(std::string_view value);

template<>
WindowAggregationMode EnumUtil::FromString<WindowAggregationMode>(std::string_view value);

template<>
WindowBoundary EnumUtil::FromString<WindowBoundary>(std::string_view value);

template<>
WindowExcludeMode EnumUtil::FromString<WindowExcludeMode>(std::string_view value);

template<>
WindowMergeSortStage EnumUtil::FromString<WindowMergeSortStage>(std::string_view value);


}
